#1060 Renamed testcases in examples and make it point to examples. De…
dynawo/dynawo pull request #1061
Opened 2020-08-04 08:03 UTC by gautierbureau

…leted sources from distrib.

2020-08-04 08:04 UTC, gautierbureau commented
This commit will need to be merged right before we do the next release. (I do it now to not forget it)

2020-08-04 09:40 UTC, gautierbureau commented
@adriguir fyi

2022-05-11 11:30 UTC, rosiereflo requested changes
Given the time between the creation and the merge of this PR, could you please make sure this is still doing what is expected?

2022-05-11 11:30 UTC, rosiereflo commented on util/envDynawo.sh
> +      if [ "$DYNAWO_LIBRARY_TYPE" = "SHARED" ]; then
Needs to be removed

2022-05-17 13:40 UTC, gautierbureau commented on util/envDynawo.sh
> +      if [ "$DYNAWO_LIBRARY_TYPE" = "SHARED" ]; then
done

2022-05-17 13:40 UTC, gautierbureau commented
> Given the time between the creation and the merge of this PR, could you please make sure this is still doing what is expected?

Yes it is ok !

2022-05-18 07:14 UTC, rosiereflo approved these changes

2022-05-18 07:14 UTC, merged