#1215 Logging able to continue previous log file
dynawo/dynawo pull request #1218
Opened 2020-10-21 09:16 UTC by lecourtoisflo

2020-10-21 10:18 UTC, rosiereflo approved these changes

2020-10-22 08:28 UTC, gautierbureau requested changes

2020-10-22 08:28 UTC, gautierbureau commented on dynawo/sources/Common/DYNTrace.h
> +    const std::string &getFilePath() const {
string& to be coherent with around

2020-10-22 08:35 UTC, lecourtoisflo commented on dynawo/sources/Common/DYNTrace.h
> +    const std::string &getFilePath() const {
OK

2020-10-22 11:36 UTC, gautierbureau approved these changes

2020-10-22 11:47 UTC, merged