902 optimization pattern
dynawo/dynawo pull request #1258
Opened 2020-11-16 14:00 UTC by lecourtoisflo

Remove pattern using interface in Dynawo API when not necessary.

2020-11-17 09:03 UTC, gautierbureau approved these changes

2020-11-17 09:23 UTC, rosiereflo requested changes

2020-11-17 09:23 UTC, rosiereflo commented on dynawo/3rdParty/libzip/include/libzip/ZipEntry.h
> +#include <archive_entry.h>
Can't we split this huge MR into 1 MR per library? This woul be to limit the risk of a massive breakage

2020-11-17 09:49 UTC, rosiereflo commented
What is the performance gain with this?

2020-11-17 10:22 UTC, lecourtoisflo commented
> What is the performance gain with this?

Performances are unchanged ; duration are within the error margin

2020-11-17 10:28 UTC, rosiereflo commented
Then we should discuss on the objective of this MR: I understood  that it was to improve performance so if we do not observe any performance gain I am not sure this should be merged as it is a big change that largely breaks code history

2020-11-17 10:29 UTC, lecourtoisflo commented
> Then we should discuss on the objective of this MR: I understood that it was to improve performance so if we do not observe any performance gain I am not sure this should be merged as it is a big change that largely breaks code history

It was more for code clarification with a potential performance increase.

2020-11-26 17:01 UTC, rosiereflo requested changes

2020-11-26 17:01 UTC, rosiereflo commented on dynawo/sources/Solvers/Common/DYNSolverImpl.hpp
> + * @file  DYNSolver.hpp
not yet renamed :)

2020-11-26 17:01 UTC, rosiereflo commented on dynawo/sources/Models/CPP/ModelNetwork/DYNNetworkComponentImpl.hpp
> + * @file  DYNNetworkComponent.hpp
not yet renamed :)

2020-11-27 13:03 UTC, lecourtoisflo commented
all NRT are OK

2020-11-30 09:11 UTC, rosiereflo approved these changes

2020-12-03 08:00 UTC, rosiereflo approved these changes

2020-12-03 08:00 UTC, merged