#1467 reducing number of variable for restorative loads with limits
dynawo/dynawo pull request #1547
Opened 2021-03-29 15:53 UTC by marcochiaramello

Closes #1467

2021-03-30 07:01 UTC, rosiereflo requested changes

2021-03-30 07:01 UTC, rosiereflo commented on dynawo/sources/Models/CPP/Components/ModelLoadRestorativeWithLimits/test/TestLoadRestorativeWithLimits.cpp
> +  ASSERT_NO_THROW(modelLoad->evalCalculatedVarI(1));
Would be nice to test the return value

2021-03-30 09:33 UTC, marcochiaramello commented on dynawo/sources/Models/CPP/Components/ModelLoadRestorativeWithLimits/DYNModelLoadRestorativeWithLimits.cpp
> +      calculatedVars_[PNum_] = evalCalculatedVarI(PNum_);
I have replaced with explicit expression to avoid this

2021-03-30 09:33 UTC, marcochiaramello commented on dynawo/sources/Models/CPP/Components/ModelLoadRestorativeWithLimits/test/TestLoadRestorativeWithLimits.cpp
> +  ASSERT_NO_THROW(modelLoad->evalCalculatedVarI(1));
done! thx

2021-03-30 09:39 UTC, rosiereflo requested changes

2021-03-30 09:39 UTC, rosiereflo commented on dynawo/sources/Models/CPP/Components/ModelLoadRestorativeWithLimits/DYNModelLoadRestorativeWithLimits.cpp
> +      calculatedVars_[PNum_] = P0Pu_ * pow_dynawo(U/yLocal_[UfYNum_], alpha_);;
useless ; (harmless I know ;))

2021-03-31 07:23 UTC, rosiereflo approved these changes

2021-03-31 08:30 UTC, gautierbureau approved these changes

2021-03-31 09:40 UTC, merged