#1615 Fix XML initialization for some unit tests
dynawo/dynawo pull request #1616
Opened 2021-04-26 08:32 UTC by valleefred

2021-04-27 06:24 UTC, gautierbureau requested changes

2021-04-27 06:24 UTC, gautierbureau commented on dynawo/sources/API/CRT/test/TestXmlImporter.cpp
> +// Copyright (c) 2015-2021, RTE (http://www.rte-france.com)
year of all copyright should not be changed when you edit a file.

2021-04-27 06:24 UTC, gautierbureau commented on dynawo/sources/API/CRV/test/TestXmlImporter.cpp
> +// Copyright (c) 2015-2021, RTE (http://www.rte-france.com)
same

2021-04-27 06:24 UTC, gautierbureau commented on dynawo/sources/API/DYD/test/Test.cpp
> +// Copyright (c) 2015-2021, RTE (http://www.rte-france.com)
same

2021-04-27 06:24 UTC, gautierbureau commented on dynawo/sources/Test/initXml.cpp
> +// Copyright (c) 2015-2021, RTE (http://www.rte-france.com)
When a new file is created the year of the copyright should be the year it is created so don't add 2015, and this file was created in 2021.

2021-04-30 12:02 UTC, gautierbureau commented
I would prefer if you could squash the two commits before merging it. thanks

2021-04-30 13:02 UTC, valleefred commented
> I would prefer if you could squash the two commits before merging it. thanks

Thanks, I've just learned how to squash ! ;-)

2021-05-03 07:27 UTC, gautierbureau approved these changes

2021-05-10 06:51 UTC, rosiereflo requested changes

2021-05-10 06:51 UTC, rosiereflo commented on dynawo/sources/API/CRT/test/TestXmlImporter.cpp
> +// This file is part of Dynawo, an hybrid C++/Modelica open source suite
Please do not modify the copyrights of existing files

2021-05-10 08:01 UTC, rosiereflo approved these changes

2021-05-10 09:19 UTC, merged