#1676 resolve ACPIN inconsistency in bus model and remove PWPIN
dynawo/dynawo pull request #1697
Opened 2021-05-31 13:13 UTC by marcochiaramello

Closes #1676

2021-05-31 15:28 UTC, rosiereflo requested changes

2021-05-31 15:28 UTC, rosiereflo commented on dynawo/sources/Models/CPP/ModelNetwork/test/TestBus.cpp
> -  ASSERT_EQ(nbAlias, 4);
ASSERT_EQ(nbAlias, 0)?

2021-05-31 15:36 UTC, marcochiaramello commented on dynawo/sources/Models/CPP/ModelNetwork/test/TestBus.cpp
> -  ASSERT_EQ(nbAlias, 4);
ok!

2021-06-01 06:47 UTC, rosiereflo approved these changes

2021-06-01 06:47 UTC, merged