#1639 Add the notion of opposite events file for timeline filtering
dynawo/dynawo pull request #1722
Opened 2021-06-10 06:40 UTC by rosiereflo

2021-06-10 06:47 UTC, rosiereflo commented
@adriguir FYI

2021-06-10 09:58 UTC, rosiereflo commented
With the latest version we need ~5s to filter a timeline with initially 81k lines and reduce it to ~22k lines.
Most of the time is spent in reading the initial timeline.

2021-06-10 13:14 UTC, valleefred requested changes

2021-06-14 11:51 UTC, gautierbureau approved these changes

2021-06-16 13:45 UTC, rosiereflo commented on dynawo/sources/Common/Dictionaries/validateDictionaries.py
> +    def generate_opposite_events_file(self, op_events_dir=None):
solved

2021-06-16 13:45 UTC, rosiereflo commented on dynawo/sources/Common/Dictionaries/validateDictionaries.py
> +                print ("File : DYN"+self.name+"_oppositeEvents.dic, the key " + key1 + " is not found in dictionary file.")
solved

2021-06-16 13:45 UTC, rosiereflo commented on dynawo/sources/Common/Dictionaries/validateDictionaries.py
> +                print ("File : DYN"+self.name+"_oppositeEvents.dic, the key " + key2 + " is not found in dictionary file.")
solved

2021-06-16 13:46 UTC, rosiereflo commented on dynawo/sources/Common/Dictionaries/validateDictionaries.py
> +    def copy_delete_opposite_event_file(self, cpp_dir=None):
solved

2021-06-16 13:46 UTC, rosiereflo commented on dynawo/sources/Common/test/TestValidateDic.cpp
> +  remove("dic/allInOne/AIOMyTimeline_oppositeEvents.py");
solved

2021-06-16 13:46 UTC, rosiereflo commented on dynawo/sources/Common/CMakeLists.txt
>  add_custom_target(create_keys_files ALL DEPENDS ${DYNAWO_DICTIONARIES})
solved

2021-06-16 13:46 UTC, rosiereflo commented on util/timeline_filter/timelineFilter.py
> +        if (len(array) ==4):
solved

2021-06-17 08:24 UTC, merged