#125 fix clang compilation -Wunused-exception-parameter -Wunused-private-field
dynawo/dynawo pull request #1896
Opened 2021-09-30 14:07 UTC by valleefred

Removing `-Wno-unused-exception-parameter` causes an error !

`error: unused exception parameter 'e' [-Werror,-Wunused-exception-parameter]`

Removing `-Wno-unused-private-field` causes an error !

`error: private field 'rmModels_' is not used [-Werror,-Wunused-private-field]`

`-Wno-unused-macros` is useless and can be removed.

See #125

2021-11-18 07:59 UTC, gautierbureau requested changes

2021-11-18 07:59 UTC, gautierbureau commented on dynawo/sources/Modeler/Common/DYNCompiler.cpp
> +  (void)rmModels_;  // shut up clang -Wunused-private-field
ok but we avoid using it elsewhere so better have the same coding style

2021-11-18 09:23 UTC, valleefred commented on dynawo/sources/Modeler/Common/DYNCompiler.cpp
> +  (void)rmModels_;  // shut up clang -Wunused-private-field
Ok done

2021-11-19 14:28 UTC, gautierbureau approved these changes

2021-11-19 14:28 UTC, gautierbureau commented
conflict

2021-11-22 08:11 UTC, merged