#1952 Improvements to continuous integration
dynawo/dynawo pull request #1958
Opened 2021-11-03 11:11 UTC by zamarrenolm

Closes #1952

2021-11-04 18:30 UTC, gautierbureau commented
Another issue is that currently the tag nightly is never updated. Maybe we need to delete it before creating the release very night. Maybe it can be done in another PR

2021-11-05 07:25 UTC, gautierbureau commented
And it seems that the upload is now failing for some reason https://github.com/dynawo/dynawo/actions/runs/1423802129

2021-11-05 07:45 UTC, zamarrenolm commented
> And it seems that the upload is now failing for some reason https://github.com/dynawo/dynawo/actions/runs/1423802129

It seems related to failures in the connection with github servers. The issue is described in https://github.com/actions/upload-artifact/issues/116. The upload of artifacts retries with exponential back-off, to reduce the likelihood of these failures.

I've manually re-run the jobs to see if it was a temporary error.

2021-11-05 07:46 UTC, zamarrenolm commented
> Another issue is that currently the tag nightly is never updated. Maybe we need to delete it before creating the release very night. Maybe it can be done in another PR

We will verify this. It has also been noted by @lecourtoisflo.

2021-12-01 15:29 UTC, gautierbureau requested changes

2021-12-01 15:29 UTC, gautierbureau commented on .github/workflows/tools.sh
> +greet()
function is not used

2021-12-01 15:30 UTC, gautierbureau commented
Could you squash the commits after your correction and then I will merge it

2021-12-01 16:14 UTC, zamarrenolm commented
> Could you squash the commits after your correction and then I will merge it

Squash and rebase on current master ?

2021-12-01 16:29 UTC, zamarrenolm commented
Commits squashed

2021-12-01 20:49 UTC, gautierbureau approved these changes

2021-12-01 20:49 UTC, merged