#2053 Fix get slack node bus id
dynawo/dynawo pull request #2055
Opened 2021-12-16 10:29 UTC by zamarrenolm

Closes #2053

2021-12-16 12:23 UTC, lecourtoisflo approved these changes

2022-01-12 16:12 UTC, gautierbureau approved these changes

2022-01-13 13:46 UTC, rosiereflo requested changes

2022-01-13 15:12 UTC, rosiereflo commented on dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNNetworkInterfaceIIDM.cpp
> +      return false;
yes sorry I missed the encapsulation in a lambda expression

2022-01-13 15:12 UTC, rosiereflo approved these changes

2022-01-13 16:57 UTC, merged