#1897 refactoring and completion on Static Var Compensator models
dynawo/dynawo pull request #2056
Opened 2021-12-16 13:04 UTC by marcochiaramello

Closes #1897

2021-12-16 15:15 UTC, cossartque requested changes

2021-12-16 15:15 UTC, cossartque commented on dynawo/sources/Models/Modelica/PreassembledModels/StaticVarCompensatorPVPropSimplified.xml
> +    Copyright (c) 2015-2021, RTE (http://www.rte-france.com)
2021 (for other files also)

2021-12-16 15:15 UTC, cossartque commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/StaticVarCompensators/SVarCPV.mo
>    extends BaseControls.Parameters.Params_ModeHandling;
No import needed ?

2021-12-16 15:15 UTC, cossartque commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/StaticVarCompensators/SVarCPV.mo
>    parameter Types.VoltageModulePu U0Pu  "Start value of voltage amplitude at injector terminal in p.u (base UNom)";
One space and not two before comment (sorry, I think it was my mistake) (also for other parameters)

2021-12-16 15:15 UTC, cossartque commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/StaticVarCompensators/SVarCPV.mo
Please remove blank line after equation

2021-12-16 15:15 UTC, cossartque commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/StaticVarCompensators/SVarCPVProp.extvar
> +    Copyright (c) 2015-2020, RTE (http://www.rte-france.com)
2021

2021-12-16 15:15 UTC, cossartque commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/StaticVarCompensators/SVarCPVProp.mo
> +
Why not also having a BStatus for the prop models ?

2021-12-16 15:19 UTC, marcochiaramello commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/StaticVarCompensators/CMakeLists.txt
> -  SVarCPVRemote_INIT.mo
yes!

2021-12-16 15:19 UTC, marcochiaramello commented on .gitignore
> +nrt/data/*/*/*/*/outputs*/
no, references are kept

2022-01-03 12:44 UTC, marcochiaramello commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/StaticVarCompensators/CMakeLists.txt
> +  SVarCPVProp.mo
done

2022-01-03 13:25 UTC, cossartque approved these changes

2022-01-03 15:02 UTC, merged