#2049 modification submodel parameter
dynawo/dynawo pull request #2059
Opened 2021-12-21 12:07 UTC by AlexPoiron

closes #2049

2021-12-21 12:12 UTC, lecourtoisflo commented on dynawo/sources/Modeler/ModelManager/DYNModelManager.cpp
> +  mergedParametersSet_ = mergedParametersSet;
mergedParametersSet_ is not used any where else. Do we need to keep it ?

2021-12-21 12:13 UTC, lecourtoisflo requested changes

2021-12-21 12:13 UTC, lecourtoisflo commented on dynawo/sources/Modeler/ModelManager/DYNModelModelica.h
> +   *
Missing return comment

2022-01-13 10:20 UTC, rosiereflo requested changes

2022-01-13 10:20 UTC, rosiereflo commented on dynawo/sources/Modeler/ModelManager/DYNModelManager.cpp
> +  if (modelModelica()->isDataStructIsInitialized()) {
Please call setSubModelParameters in init method to avoid duplicated  code

2022-01-31 07:59 UTC, rosiereflo approved these changes

2022-02-01 07:56 UTC, merged