2014 wecc pv vsource model
dynawo/dynawo pull request #2062
Opened 2022-01-03 15:01 UTC by bongrainmat

2022-01-04 10:17 UTC, cossartque requested changes

2022-01-04 10:17 UTC, cossartque commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Photovoltaics/WECC/PVVoltageSource.mo
> +model PVVoltageSource "WECC PV model with a voltage source as interface with the grid"
Weird arrows to check

2022-01-04 10:17 UTC, cossartque commented on dynawo/sources/Models/Modelica/Dynawo/Examples/Photovoltaics/WECC/PVVoltageSource.mo
> +  Dynawo.Electrical.Photovoltaics.WECC.PVVoltageSource PV(DDn = 20, DPMax = 999, DPMin = -999, DUp = 0.001, Dbd = 0.01, Dbd1 = -0.1, Dbd2 = 0.1, EMax = 999, EMin = -999, FDbd1 = 0.004, FDbd2 = 1, FEM
The parameters don't appear in the diagram view

2022-01-04 10:17 UTC, cossartque commented on dynawo/sources/Models/Modelica/PreassembledModels/PhotovoltaicsWeccVoltageSource.xml
> +    Copyright (c) 2015-2021, RTE (http://www.rte-france.com)
2021

2022-01-04 10:17 UTC, cossartque commented on dynawo/sources/Models/Modelica/PreassembledModels/PhotovoltaicsWeccVoltageSource.xml
> +    <dyn:unitDynamicModel id="photovoltaicsV" name="Dynawo.Electrical.Photovoltaics.WECC.PVVoltageSource" initName="Dynawo.Electrical.Photovoltaics.WECC.PVVoltageSource_INIT"/>
It could still be called photovoltaics and not photovoltaicsV as the VoltageSource is already in the name

2022-01-04 10:17 UTC, cossartque commented on examples/DynaSwing/WECCPVVoltageSource/solvers.par
> +    Copyright (c) 2015-2021, RTE (http://www.rte-france.com)
2021

2022-01-04 13:16 UTC, bongrainmat commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Photovoltaics/WECC/PVVoltageSource_INIT.mo
> +  USourceq0Pu = 0 + Iq0Pu * RSourcePu + Id0Pu * XSourcePu;
I have changed U0Pu in UInj0Pu in USourced0Pu = UInj0Pu + Id0Pu * RSourcePu - Iq0Pu * XSourcePu;
i have kept : USourceq0Pu = 0 + Iq0Pu * RSourcePu + Id0Pu * XSourcePu;

2022-01-04 13:17 UTC, bongrainmat commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Photovoltaics/WECC/PVVoltageSource_INIT.mo
> +  iSource0Pu = - i0Pu * SystemBase.SnRef / SNom;
I have reused the PVCurrentSource Init model equation's here. Frankly, i don't know.

2022-01-04 13:18 UTC, bongrainmat commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Photovoltaics/WECC/PVVoltageSource_INIT.mo
> +  UPhaseSource0 = ComplexMath.arg(uSource0Pu);
yes in the transform for Id0Pu and Iq0Pu calculation.

2022-01-04 13:18 UTC, bongrainmat commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Sources/CMakeLists.txt
> +  InjectorURI.mo
no init model is needed. For IDQ, you don't use the init either.

2022-01-06 16:09 UTC, cossartque approved these changes

2022-01-06 16:56 UTC, merged