#2104 Add a script to compare constraint values with a tolerance.
dynawo/dynawo pull request #2139
Opened 2022-01-28 12:48 UTC by rosiereflo

Also fix the dump of txt constraints

2022-01-28 15:16 UTC, marcochiaramello requested changes

2022-01-28 15:16 UTC, marcochiaramello commented on util/nrt_diff/XMLUtils.py
> +        return None
should not exit here?

2022-02-02 08:49 UTC, rosiereflo commented on util/nrt_diff/XMLUtils.py
> +        return None
solved

2022-02-04 08:15 UTC, marcochiaramello approved these changes

2022-02-04 09:00 UTC, merged