#2154 New hysteresis without initial equation
dynawo/dynawo pull request #2155
Opened 2022-02-03 17:15 UTC by ErwanGuichard49

2022-02-04 12:45 UTC, cossartque requested changes

2022-02-04 12:45 UTC, cossartque commented on dynawo/sources/Models/Modelica/Dynawo/NonElectrical/Blocks/NonLinear/Hysteresis.mo
> +
copyright

2022-02-04 16:06 UTC, ErwanGuichard49 commented on dynawo/sources/Models/Modelica/Dynawo/NonElectrical/Blocks/NonLinear/Hysteresis.mo
> +
Added

2022-02-04 16:32 UTC, cossartque approved these changes

2022-02-07 07:43 UTC, cossartque approved these changes

2022-02-07 08:56 UTC, merged