#2190 Add order 1 prediction in SIM solver.
dynawo/dynawo pull request #2197
Opened 2022-03-01 09:50 UTC by gautierbureau

close #2190

2022-03-04 06:31 UTC, rosiereflo requested changes
Before reviewing, please add unit tests and a testcase that illustrates this features

2022-03-04 10:46 UTC, rosiereflo commented
Please also adapt the documentation

2024-05-13 13:45 UTC, gautierbureau commented
Done for both comments

2024-05-22 15:25 UTC, rosiereflo requested changes

2024-05-22 15:25 UTC, rosiereflo commented on dynawo/sources/Solvers/FixedTimeStep/SolverSIM/DYNSolverSIM.cpp
> +bool SolverSIM::hasPrediction() {
this method should be const

2024-05-22 15:25 UTC, rosiereflo commented on dynawo/sources/Solvers/FixedTimeStep/SolverSIM/DYNSolverSIM.cpp
> +      bool noInitSetup = false;
those bool cpould be const

2024-05-22 15:25 UTC, rosiereflo commented on dynawo/sources/Solvers/FixedTimeStep/SolverSIM/test/jobs/solverTestPrediction.dyd
> +    Copyright (c) 2015-2019, RTE (http://www.rte-france.com)
2024

2024-05-22 15:25 UTC, rosiereflo commented on nrt/data/SIMOrder1Prediction/Test.crv
> +    Copyright (c) 2021, RTE (http://www.rte-france.com)
2024 (same for all)

2024-05-23 06:59 UTC, gautierbureau commented on dynawo/sources/Solvers/FixedTimeStep/DYNSolverCommonFixedTimeStep.cpp
> +    model_->reinitMode();
I just moved the initial one below this new piece of code

2024-05-23 09:28 UTC, rosiereflo commented on dynawo/sources/Solvers/FixedTimeStep/DYNSolverCommonFixedTimeStep.cpp
> +    model_->reinitMode();
yes, but why? Does the code above modify the modes?

2024-05-23 12:48 UTC, gautierbureau commented on dynawo/sources/Solvers/FixedTimeStep/SolverSIM/DYNSolverSIM.cpp
> +  parameters_.insert(make_pair("order1Prediction", ParameterSolver("order1Prediction", VAR_TYPE_BOOL, optional)));
yes

2024-05-23 12:48 UTC, gautierbureau commented on dynawo/sources/Solvers/FixedTimeStep/SolverSIM/DYNSolverSIM.cpp
> +bool SolverSIM::hasPrediction() {
done

2024-05-23 13:07 UTC, gautierbureau commented on dynawo/sources/Solvers/FixedTimeStep/SolverSIM/test/jobs/solverTestPrediction.dyd
> +    Copyright (c) 2015-2019, RTE (http://www.rte-france.com)
done

2024-05-23 13:07 UTC, gautierbureau commented on nrt/data/SIMOrder1Prediction/Test.crv
> +    Copyright (c) 2021, RTE (http://www.rte-france.com)
done

2024-05-24 07:21 UTC, gautierbureau commented on dynawo/sources/Solvers/FixedTimeStep/SolverSIM/DYNSolverSIM.cpp
> +  parameters_.insert(make_pair("order1Prediction", ParameterSolver("order1Prediction", VAR_TYPE_BOOL, optional)));
in fact it needs to be false, the name of the parameter indicates the parameter will be optional and not its value ! Same thing is done in SolverCommonFixedTimeStep (from where I copied it !). I added a comment !

2024-05-24 08:34 UTC, rosiereflo approved these changes

2024-05-24 10:05 UTC, merged