#2247 add possibility to connect a calculated discrete variable to a …
dynawo/dynawo pull request #2256
Opened 2022-04-07 14:30 UTC by marcochiaramello

…state discrete variable

2022-04-08 07:03 UTC, rosiereflo requested changes

2022-04-08 07:03 UTC, rosiereflo commented on dynawo/sources/Modeler/Common/DYNConnectorCalculatedDiscreteVariable.h
> + * class ConnectorCalculatedDiscreteVariable
Please add a description

2022-04-08 07:03 UTC, rosiereflo commented on dynawo/sources/Modeler/Common/DYNConnectorCalculatedDiscreteVariable.h
> +  double prevZValue_;
not commented

2022-04-08 07:03 UTC, rosiereflo commented on dynawo/sources/Modeler/Common/DYNModelMulti.h
> +   * @param subModel1 submodel owning the calculated variable to connect
subModel and variable

2022-04-08 07:56 UTC, marcochiaramello commented on dynawo/sources/Modeler/Common/DYNConnectorCalculatedDiscreteVariable.cpp
> + * @brief Connector to use when connecting to a calculated variable
ok!

2022-04-08 07:56 UTC, marcochiaramello commented on dynawo/sources/Modeler/Common/DYNConnectorCalculatedDiscreteVariable.cpp
> +  model_->getIndexesOfVariablesUsedForCalculatedVarI(indexCalculatedVariable_, varExtIndexes_);
done

2022-04-08 08:02 UTC, marcochiaramello commented on dynawo/sources/Modeler/Common/DYNConnectorCalculatedDiscreteVariable.cpp
> +  gEquationIndex_[0] = std::string("prevZValue !=  model_->evalCalculatedVarI(indexCalculatedVariable_)");
done

2022-04-08 08:03 UTC, marcochiaramello commented on dynawo/sources/Modeler/Common/DYNConnectorCalculatedDiscreteVariable.cpp
> +  gLocal_[0] = ROOT_DOWN;
indeed!thx

2022-04-08 08:03 UTC, marcochiaramello commented on dynawo/sources/Modeler/Common/DYNConnectorCalculatedDiscreteVariable.cpp
> +  prevZValue_ = model_->getCalculatedVar(indexCalculatedVariable_);
done

2022-04-08 08:03 UTC, marcochiaramello commented on dynawo/sources/Modeler/Common/DYNConnectorCalculatedDiscreteVariable.h
> +  double prevZValue_;
thx, done

2022-04-08 08:03 UTC, marcochiaramello commented on dynawo/sources/Modeler/Common/DYNModelMulti.h
> +   * @param subModel1 submodel owning the calculated variable to connect
ok

2022-04-08 08:03 UTC, marcochiaramello commented on dynawo/sources/Modeler/Common/DYNConnectorCalculatedDiscreteVariable.h
> + * class ConnectorCalculatedDiscreteVariable
done

2022-04-08 08:05 UTC, marcochiaramello commented on dynawo/sources/Modeler/Common/DYNConnectorCalculatedDiscreteVariable.cpp
> +  gLocal_[0] = doubleNotEquals(prevZValue_, model_->evalCalculatedVarI(indexCalculatedVariable_)) ? ROOT_UP : ROOT_DOWN;
yes, you are right but I do not see an easy way to avoid this without breaking the logic of evalG evalZ use in a submodel

2022-04-08 10:17 UTC, rosiereflo requested changes

2022-04-08 10:17 UTC, rosiereflo commented on dynawo/sources/Modeler/Common/DYNConnectorCalculatedDiscreteVariable.h
> +  std::vector<int> varExtIndexes_;  ///< Indexes of variables on which depends the calculated variable
Useless

2022-04-08 10:17 UTC, rosiereflo commented on dynawo/sources/Modeler/Common/DYNConnectorCalculatedDiscreteVariable.h
> + * @brief Connector to use when connecting to a calculated variable
Should be the same as .h

2022-04-08 10:17 UTC, rosiereflo commented on dynawo/sources/Modeler/Common/test/Test.cpp
> +                              modelMulti->findSubModelByName("subModel2"), "MyDiscreteVar_value"));
Would it be possible to write some unit tests about the new submodel? (testing the root is raised when required ...)

2022-04-12 08:14 UTC, rosiereflo approved these changes

2022-04-19 11:53 UTC, gautierbureau requested changes

2022-04-19 11:53 UTC, gautierbureau commented on dynawo/sources/Modeler/Common/test/Test.cpp
> +  // void defineElements(std::vector<Element>&, std::map<std::string, int >&) {
why keep this commented out ?

2022-04-19 11:53 UTC, gautierbureau commented on dynawo/sources/Modeler/Common/test/Test.cpp
> +    return;
return is void why the need for a return ?

2022-04-25 11:39 UTC, gautierbureau approved these changes

2022-04-26 11:34 UTC, merged