2270 infinite bus impedance
dynawo/dynawo pull request #2285
Opened 2022-04-25 13:13 UTC by GerardThevenon

**Checklist before requesting a review**

*use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes*

- [ ] unit tests and non regression tests were added (new model, new feature and bug fix)
- [ ] main documentation was updated (update of input/output file, 3rd party, model, repository organization, solver)
- [ ] example documentations were updated (new example in examples folder)
- [ ] if this PR modifies the parameters or inputs/outputs of a model: the corresponding xsl was added in util/xsl
- [ ] if this commit targets a release branch: the corresponding milestone was added in the ticket and in this PR

2022-05-09 13:26 UTC, cossartque requested changes

2022-05-09 13:26 UTC, cossartque commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Buses/InfiniteBusWithImpedance.mo
> +  Dynawo.Electrical.Lines.Line impedance(BPu = BPu, GPu = GPu, RPu = RPu, XPu = XPu) annotation(
G = 0 and B = 0 (cf INIT model)

2022-05-09 13:26 UTC, cossartque commented on dynawo/sources/Models/Modelica/PreassembledModels/Measurements.xml
> +  <!-- This model measures the voltage at the left-hand-side terminal -->
This model measures the voltage, the current, etc. (also there is not really a left-hand side as there is no impedance, left = right).

2022-05-11 08:38 UTC, GerardThevenon commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Buses/InfiniteBusWithImpedance.mo
> +  //Bus parameters
I have put them here because they are the ones you can see when double-clicking the infinite bus in the diagram view.

2022-05-11 09:28 UTC, GerardThevenon commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Buses/InfiniteBusWithImpedance.mo
> +  parameter Types.ComplexCurrentPu iMachine0Pu "Initial current at terminal of the machine in pu (base UNom, SnRef)";
uBus0Pu is already used in the INIT model, so I have changed to uTerminal0Pu.

2022-05-11 14:53 UTC, cossartque requested changes

2022-05-11 14:53 UTC, cossartque commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Utilities/Measurements.mo
> +  Modelica.Blocks.Interfaces.RealOutput QPu "Reactive power on side 1 in pu (base SnRef)" annotation(
at terminal 1 in pu (base SnRef) (receptor convention)

2022-05-11 14:53 UTC, cossartque commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Buses/InfiniteBusWithImpedance.mo
> +  //Bus parameters
Yes but they are calculated by the INIT model (when used in dynawo), and not given by the user. I prefer to have them with the initial parameters, thanks.

2022-05-11 14:53 UTC, cossartque commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Buses/InfiniteBusWithImpedance.mo
> +  parameter Types.PerUnit XPu "Line reactance in pu (base SnRef)";
"Reactance in pu (base UNom, SnRef)"

2022-05-11 14:53 UTC, cossartque commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Buses/InfiniteBusWithImpedance.mo
> +    V(re(start = ComplexMath.real(uTerminal0Pu)), im(start = ComplexMath.imag(uTerminal0Pu))),
Could you just use uTerminal0Pu.re ? (same for im, and for the current)

2022-05-11 14:53 UTC, cossartque commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Buses/InfiniteBusWithImpedance.mo
> +  parameter Types.ComplexVoltagePu uTerminal0Pu "Initial voltage at terminal in pu (base UNom)";
Initial complex voltage at terminal in pu (base UNom)

2022-05-11 14:53 UTC, cossartque commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Buses/InfiniteBusWithImpedance_INIT.mo
> +  //Line parameters
Same comments as in the dynamic model (you can copy/paste the three lines)

2022-05-11 14:53 UTC, cossartque commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Buses/InfiniteBusWithImpedance_INIT.mo
> +  Types.ComplexVoltagePu uTerminal0Pu "Initial voltage at terminal in pu (base UNom)";
Initial complex voltage

2022-05-11 14:53 UTC, cossartque commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Buses/InfiniteBusWithImpedance_INIT.mo
> +  Types.ComplexApparentPowerPu STerminal0Pu "Initial apparent power at terminal in pu (base SnRef)";
Also, it "s" and not "S"

2022-05-11 14:53 UTC, cossartque commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Buses/InfiniteBusWithImpedance_INIT.mo
> +  Types.ComplexCurrentPu iTerminal0Pu "Initial current at terminal in pu (base UNom, SnRef)";
(receptor convention)

2022-05-11 14:53 UTC, cossartque commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Buses/InfiniteBusWithImpedance_INIT.mo
> +  uTerminal0Pu - uBus0Pu = ZPu * iTerminal0Pu;
= - ZPu * iTerminal0Pu (receptor convention)

2022-05-11 14:53 UTC, cossartque commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Buses/InfiniteBusWithImpedance_INIT.mo
> +  UBus0Pu = (uBus0Pu.re ^ 2 + uBus0Pu.im ^ 2) ^ 0.5;
You could use 'abs' here

2022-05-11 14:53 UTC, cossartque commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Buses/InfiniteBusWithImpedance_INIT.mo
> +  UPhaseBus0 = Math.atan2(uBus0Pu.im, uBus0Pu.re);
You could use 'arg' here

2022-05-12 16:07 UTC, GerardThevenon commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Utilities/Measurements.extvar
> +  <variable type="continuous" id="terminal1.i.re"/>
Actually, compilation fails with terminal2.V.re and terminal2.V.im, that is why I put terminal1.i.re and terminal2.i.im
I have just checked again.

2022-05-13 08:32 UTC, cossartque commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Utilities/Measurements.extvar
> +  <variable type="continuous" id="terminal1.i.re"/>
What is the error given ?

2022-05-13 12:16 UTC, cossartque commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Buses/InfiniteBusWithImpedance_INIT.mo
> +  uTerminal0Pu - uBus0Pu = - ZPu * iTerminal0Pu;
I didn't see it was uTerminal- uBus, so it's ZPu * iTerminal and not - ZPu * iTerminal0Pu, my bad ! I do the correction

2022-05-13 12:29 UTC, cossartque approved these changes

2022-05-13 13:33 UTC, merged