#2366 introducing warm and flat start for model network
dynawo/dynawo pull request #2473
Opened 2022-09-07 09:53 UTC by marcochiaramello

**Checklist before requesting a review**

*use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes*

- [ ] unit tests and non regression tests were added (new model, new feature and bug fix)
- [ ] main documentation was updated (update of input/output file, 3rd party, model, repository organization, solver)
- [ ] example documentations were updated (new example in examples folder)
- [ ] if this PR modifies the parameters or inputs/outputs of a model/solver: the corresponding xsl was added in util/xsl and platform DB were updated
- [ ] if this PR modifies a dictionary: the corresponding french dictionary was updated
- [ ] if this commit targets a release branch: the corresponding milestone was added in the ticket and in this PR

2022-09-07 15:05 UTC, rosiereflo requested changes

2022-09-07 15:05 UTC, rosiereflo commented on dynawo/sources/Models/CPP/ModelNetwork/DYNNetworkComponent.cpp
> +  std::map<std::string, startingPointMode_t> enumResolver = {{"flat", startingPointMode_t::FLAT},
I would put this static

2022-09-07 15:06 UTC, rosiereflo commented
There is also 1 code smell to look at

2022-09-07 15:07 UTC, marcochiaramello commented on dynawo/sources/Common/Dictionaries/DYNLog_en_GB.dic
> +StartingPointModeNotFound     =             startingPointMode %1% not found, should be warm or flat. Using warm starting point mode.
yes, ongoing :)

2022-09-08 07:38 UTC, marcochiaramello commented on dynawo/sources/Models/CPP/ModelNetwork/DYNModelBus.cpp
> +  angle0_ = bus_->getAngle0() * DEG_TO_RAD;
indeed, thx, done

2022-09-08 07:38 UTC, marcochiaramello commented on dynawo/sources/Models/CPP/ModelNetwork/DYNModelGenerator.cpp
> +  Pc_ = 0.;
done

2022-09-08 07:39 UTC, marcochiaramello commented on dynawo/sources/Models/CPP/ModelNetwork/DYNNetworkComponent.cpp
> +NetworkComponent::getStartingPointMode(std::string& startingPointMode) {
thx!

2022-09-09 08:09 UTC, cossartque commented on dynawo/sources/Models/CPP/ModelNetwork/DYNModelHvdcLink.cpp
> +  if (dcLine->getConverter1()->hasP() && dcLine->getConverter2()->hasP() && startingPointMode_ == WARM) {
What will be the values of P01_ and P02_ in FLAT ?

2022-09-09 08:09 UTC, cossartque commented on dynawo/sources/Models/CPP/ModelNetwork/DYNModelHvdcLink.cpp
> +  if (dcLine->getConverter1()->hasQ() && dcLine->getConverter2()->hasQ() && startingPointMode_ == WARM) {
What will be the values of Q01_ and Q02_ in FLAT ?

2022-09-09 08:09 UTC, cossartque commented on dynawo/sources/Models/CPP/ModelNetwork/DYNModelShuntCompensator.cpp
> +    Q = shunt_->getB(currentSection_) * vNom_ * vNom_ / SNREF;
Do we know the currentSection_ in FLAT mode ?

2022-09-09 08:09 UTC, cossartque commented on dynawo/sources/Models/CPP/ModelNetwork/DYNModelStaticVarCompensator.cpp
> +    Q0 = svc_->getReactivePowerSetPoint() / SNREF;
Same convention as getQ() for getReactivePowerSetPoint() ?

2022-09-09 08:22 UTC, marcochiaramello commented on dynawo/sources/Common/Dictionaries/DYNLog_en_GB.dic
> +StartingPointModeNotFound     =             startingPointMode %1% not found, should be warm or flat. Using warm starting point mode.
agreed, done

2022-09-09 08:29 UTC, cossartque approved these changes

2022-09-09 13:51 UTC, merged