#2480 Add a parameter Enabled0 in AC Emulation
dynawo/dynawo pull request #2481
Opened 2022-09-12 08:42 UTC by cossartque

**Checklist before requesting a review**

*use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes*

- [ ] unit tests and non regression tests were added (new model, new feature and bug fix)
- [ ] main documentation was updated (update of input/output file, 3rd party, model, repository organization, solver)
- [ ] example documentations were updated (new example in examples folder)
- [ ] if this PR modifies the parameters or inputs/outputs of a model/solver: the corresponding xsl was added in util/xsl and platform DB were updated
- [ ] if this PR modifies a dictionary: the corresponding french dictionary was updated
- [ ] if this commit targets a release branch: the corresponding milestone was added in the ticket and in this PR

2022-09-13 13:29 UTC, rosiereflo requested changes

2022-09-13 13:29 UTC, rosiereflo commented on dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNHvdcLineInterfaceIIDM.cpp
> +  if (hvdcActivePowerControl_ && hvdcActivePowerControl_->isEnabled() && hvdcActivePowerControl_->isEnabled().get()) {
I would propose:
```
bool isACEmulationEnabled = vdcActivePowerControl_ && hvdcActivePowerControl_->isEnabled() && hvdcActivePowerControl_->isEnabled().get();
 staticParameters_.insert(std::make_pair("isACEmulationEnabled", StaticParameter("isACEmulationEnabled",
                             StaticParameter::BOOL).setValue(isACEmulationEnabled)));
```

2022-09-13 13:38 UTC, cossartque commented on dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNHvdcLineInterfaceIIDM.cpp
> +  if (hvdcActivePowerControl_ && hvdcActivePowerControl_->isEnabled() && hvdcActivePowerControl_->isEnabled().get()) {
sure !

2022-09-14 08:05 UTC, rosiereflo approved these changes

2022-09-14 10:04 UTC, merged