#10 Add LoadAlphaBetaMotor model
dynawo/dynawo pull request #2492
Opened 2022-09-16 07:50 UTC by FredericSabot

closes #2491

2022-09-22 12:12 UTC, cossartque requested changes
Thanks for the model !
A few remarks, mainly coding style : 
- Always put the copyright in .mo files (with 2022 and "suite of simulation tools")
- Always put the pu base for all the parameters and variables in pu (base UNom, SNom), etc.
- Always put the convention (generator convention) or (receptor convention) when it's a current or a power

Otherwise I have no comment on the model itself, thanks !

2022-09-22 12:12 UTC, cossartque commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Loads/LoadAlphaBetaMotor.mo
> +  parameter Types.ApparentPowerModule PNom "Nominal active power consumed by a single motor (Unom base)";
Or is it an SNom ?

2022-09-22 12:12 UTC, cossartque commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Loads/LoadAlphaBetaMotor.mo
> +  parameter Types.PerUnit RsPu "Stator resistance in pu (PNom base)";
base UNom, PNom ? or base UNom, SNom ? or base UNom, SnRef ?

2022-09-22 12:12 UTC, cossartque commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Loads/LoadAlphaBetaMotor.mo
> +  parameter Types.PerUnit RrPu "Rotor resistance in pu (PNom base)";
base UNom, PNom ? or base UNom, SNom ? or base UNom, SnRef ?

2022-09-22 12:12 UTC, cossartque commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Loads/LoadAlphaBetaMotor.mo
> +  parameter Types.PerUnit XsPu "Stator leakage reactance in pu (PNom base)";
base UNom, PNom ? or base UNom, SNom ? or base UNom, SnRef ?

2022-09-22 12:12 UTC, cossartque commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Loads/LoadAlphaBetaMotor.mo
> +  parameter Types.PerUnit XrPu "Rotor leakage reactance in pu (PNom base)";
base UNom, PNom ? or base UNom, SNom ? or base UNom, SnRef ?

2022-09-22 12:12 UTC, cossartque commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Loads/LoadAlphaBetaMotor.mo
> +  parameter Types.PerUnit XmPu "Magnetizing reactance in pu (PNom base)";
base UNom, PNom ? or base UNom, SNom ? or base UNom, SnRef ?

2022-09-22 12:12 UTC, cossartque commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Loads/LoadAlphaBetaMotor.mo
> +  parameter Real H "Inertia constant (s, PNom base)";
Inertia constant in s ?

2022-09-22 12:12 UTC, cossartque commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Loads/LoadAlphaBetaMotor.mo
> +  parameter Real alpha "Active load sensitivity to voltage";
Alpha and Beta

2022-09-22 12:12 UTC, cossartque commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Loads/LoadAlphaBetaMotor.mo
> +  Types.ComplexCurrentPu isPu(re(start = is0Pu.re), im(start = is0Pu.im)) "Stator current in pu (Unom, PNom base)";
base UNom, PNom (or SNom ?)

2022-09-22 12:12 UTC, cossartque commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Loads/LoadAlphaBetaMotor.mo
> +  Types.ComplexCurrentPu isPu(re(start = is0Pu.re), im(start = is0Pu.im)) "Stator current in pu (Unom, PNom base)";
Also, for a current, please give the convention (generator convention) or (receptor convention), thanks !
Same for imPu and irPu

2022-09-22 12:12 UTC, cossartque commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Loads/LoadAlphaBetaMotor.mo
> +  Types.PerUnit cePu(start = ce0Pu) "Electrical torque in pu (PNom base)";
base PNom, omegaNom ?

2022-09-22 12:12 UTC, cossartque commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Loads/LoadAlphaBetaMotor.mo
> +  Types.PerUnit clPu(start = ce0Pu) "Load torque in pu (PNom base)";
base PNom, omegaNom ?

2022-09-22 12:12 UTC, cossartque commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Loads/LoadAlphaBetaMotor.mo
> +  Types.ActivePowerPu PLoadPu (start = PLoad0Pu) "Active power consumed by the load in pu (SnRef base)";
base SnRef

2022-09-22 12:12 UTC, cossartque commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Loads/LoadAlphaBetaMotor.mo
> +  Types.ActivePowerPu PLoadPu (start = PLoad0Pu) "Active power consumed by the load in pu (SnRef base)";
+ convention (same for Q and iLoad)

2022-09-22 12:12 UTC, cossartque commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Loads/LoadAlphaBetaMotor.mo
> +  final parameter Types.ComplexImpedancePu ZsPu = Complex(RsPu,XsPu) "Stator impedance in pu";
pu base (same for the other parameters, thanks)

2022-09-22 12:12 UTC, cossartque commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Loads/LoadAlphaBetaMotor.mo
> +  parameter Types.ComplexCurrentPu is0Pu "Start value of the stator current in pu (Unom, PNom base)";
The initial values could be kept public

2022-09-22 12:12 UTC, cossartque commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Loads/LoadAlphaBetaMotor.mo
> +    // ZmPu*imPu = (ZrPu + RrPu*(1-s)/s)*irPu; // Kirchhoff’s voltage law in the second loop
Could it be removed ?

2022-09-22 12:12 UTC, cossartque commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Loads/LoadAlphaBetaMotor_INIT.mo
> +
Copyright

2022-09-22 12:12 UTC, cossartque commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Loads/LoadAlphaBetaMotor_INIT.mo
> +  // QLoad0Pu = s0Pu.im - QMotor0Pu;
Could it be removed ?

2022-09-22 12:12 UTC, cossartque commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Loads/LoadAlphaBetaMotor_INIT.mo
> +  // ZmPu*im0Pu = (ZrPu + RrPu*(1-s0)/s0)*ir0Pu; // Kirchhoff’s voltage law in the second loop
Could it be removed ?

2022-09-23 08:18 UTC, adriguir commented
@FredericSabot thank you for the PR!
For the non technical remarks (such as coding style and so on), we can take care of the modifications ourself if you want, in order not to bother you.

2022-09-23 13:22 UTC, adriguir commented
> There are only a few modifications to do, so I can do it. I just need a reply on the ActiveMotorShare comment. Also, I am not sure what is the issue with an inertia in seconds.

Perfect, thanks! I haven't gone through the PR in details myself but @cossartque will reply to the open points as soon as possible.

2022-09-23 13:36 UTC, cossartque commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Loads/LoadAlphaBetaMotor.mo
> +  parameter Types.ApparentPowerModule PNom "Nominal active power consumed by a single motor (Unom base)";
Ok, maybe then just put this comment "Nominal active power consumed by a single motor in MW"

2022-09-23 13:37 UTC, cossartque commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Loads/LoadAlphaBetaMotor.mo
> +  parameter Types.PerUnit ActiveMotorShare "Share of active power consumed by motors in pu";
Then maybe we don't say "in pu" but we add "(between 0 and 1)" ?

2022-09-23 14:50 UTC, cossartque commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Loads/LoadAlphaBetaMotor.mo
> +  parameter Real H "Inertia constant (s, PNom base)";
It was just a proposal for the comment : Inertia constant in s (base PNom)

2022-09-23 15:01 UTC, merged