14 protections pr
dynawo/dynawo pull request #2573
Opened 2022-11-15 07:33 UTC by FredericSabot

**Checklist before requesting a review**

*use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes*

- [ ] unit tests and non regression tests were added (new model, new feature and bug fix)
- [ ] main documentation was updated (update of input/output file, 3rd party, model, repository organization, solver)
- [ ] example documentations were updated (new example in examples folder)
- [ ] if this PR modifies the parameters or inputs/outputs of a model/solver: the corresponding xsl was added in util/xsl and platform DB were updated
- [ ] if this PR modifies a dictionary: the corresponding french dictionary was updated
- [ ] if this commit targets a release branch: the corresponding milestone was added in the ticket and in this PR

Closes #2572

2022-11-25 07:54 UTC, rosiereflo commented
@cossartque I assigned this review to you, please feel free to reassign it to someone else from the model team

2022-11-30 14:00 UTC, cossartque commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Protections/DistanceProtectionLineSide1.mo
> +  parameter Real R1Pu "Resistive reach of zone 1 in pu (base UNom, SNom)";
Types.PerUnit could be used for all R and X

2022-11-30 14:01 UTC, cossartque commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Protections/DistanceProtectionLineSide1.mo
> +  parameter Real R1Pu "Resistive reach of zone 1 in pu (base UNom, SNom)";
base UNom, SNom or UNom, SnRef ? If it is for a line, I think it should be SnRef=100MVA.

2022-11-30 14:19 UTC, cossartque commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Protections/DistanceProtectionLineSide1.mo
> +  Types.ActivePowerPu PMonitoredPu "Monitored active power in pu (base SNom)";
SNom or SnRef ?

2022-11-30 14:20 UTC, cossartque commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Protections/DistanceProtectionLineSide1.mo
> +  Types.ActivePowerPu PMonitoredPuFilter "Filtered value of PMonitoredPu";
in pu (base SnRef)

2022-11-30 14:20 UTC, cossartque commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Protections/DistanceProtectionLineSide1.mo
> +  Types.ReactivePowerPu QMonitoredPu "Monitored reactive power in pu (base SNom)";
same

2022-11-30 14:20 UTC, cossartque commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Protections/DistanceProtectionLineSide1.mo
> +  Types.ReactivePowerPu QMonitoredPuFilter "Filtered value of QMonitoredPu";
same

2022-11-30 14:22 UTC, cossartque commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Protections/DistanceProtectionLineSide1.mo
> +  Types.Time tThresholdReached1(start = Constants.inf) "Time when enters zone 1";
in s

2022-11-30 14:22 UTC, cossartque commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Protections/DistanceProtectionLineSide1.mo
> +    if time < 0.1 then  //TODO: clean initialisation, and understand why a filter is needed
Why do you need this ?

2022-11-30 14:25 UTC, cossartque commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Protections/DistanceProtectionLineSide2.mo
> +within Dynawo.Electrical.Controls.Protections;
Same comments as for side 1

2022-11-30 14:27 UTC, cossartque commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Protections/DistanceProtectionLineSide2.mo
> +
Also, could we try to find a way to make a single model with an integer parameter Side that could be 3 or 4. This would avoid duplicated code.

2022-11-30 14:27 UTC, cossartque commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Protections/DistanceProtectionLineSide2.mo
> +  elsewhen not (Z.re <= R1Pu and Z.im <= X1Pu and Z.re > -Z.im) and pre(tThresholdReached1) <> Constants.inf  then
only one space before "then" (several occurrences in the model)

2022-11-30 14:29 UTC, cossartque commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Protections/DistanceProtectionLineSide2LoadBlinder.mo
> +within Dynawo.Electrical.Controls.Protections;
same remarks as side 1.
Also, maybe we could have a single model

2022-11-30 14:30 UTC, cossartque commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Protections/DistanceProtectionLineSide1LoadBlinder.mo
> +model DistanceProtectionLineSide1LoadBlinder "Simple triangular distance relay, disconnects side 1 of the protected line when the apparent impedance in within a protected zone for longer than a set d
Maybe we could have a base model that is shared with DistanceProtectionLineSide1 ?

2022-11-30 14:31 UTC, cossartque commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Protections/DistanceProtectionLineSide1LoadBlinder.mo
> +  parameter Types.Time T1 "Time delay of trip in zone 1";
in s

2022-11-30 14:31 UTC, cossartque commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Protections/DistanceProtectionLineSide1LoadBlinder.mo
> +  parameter Real R1Pu "Resistive reach of zone 1 in pu (base UNom, SNom)";
same comments as for DistanceProtectionLineSide1

2022-11-30 14:31 UTC, cossartque commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Protections/DistanceProtectionLineSide1LoadBlinder.mo
> +  parameter Real BlinderAnglePu "Load angle of the load blinder (in rad)";
Types.Angle

2022-11-30 14:31 UTC, cossartque commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Protections/DistanceProtectionLineSide1LoadBlinder.mo
> +  parameter Real BlinderAnglePu "Load angle of the load blinder (in rad)";
in rad not in ()

2022-11-30 14:31 UTC, cossartque commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Protections/DistanceProtectionLineSide1LoadBlinder.mo
> +  parameter Real BlinderReachPu "Reach in the Z plane of the load blinder in pu (base UNom, SNom)";
SNom or SnRef ?

2022-11-30 14:32 UTC, cossartque commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Protections/DistanceProtectionLineSide1LoadBlinder.mo
> +  parameter Real tFilter = 0.001;
comment

2022-11-30 14:32 UTC, cossartque commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Protections/DistanceProtectionLineSide1LoadBlinder.mo
> +  Types.ActivePowerPu PMonitoredPuFilter "Filtered value of PMonitoredPu";
unit and pu base

2022-11-30 14:32 UTC, cossartque commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Protections/DistanceProtectionLineSide1LoadBlinder.mo
> +  Types.ReactivePowerPu QMonitoredPuFilter "Filtered value of QMonitoredPu";
unit and pu base

2022-11-30 14:32 UTC, cossartque commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Protections/DistanceProtectionLineSide1LoadBlinder.mo
> +  Complex Z "Apparent impedance in pu (base UNom, SNom)";
SNom or SnRef ?

2022-11-30 14:33 UTC, cossartque commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Protections/DistanceProtectionLineSide1LoadBlinder.mo
> +  Types.Time tThresholdReached1(start = Constants.inf) "Time when enters zone 1";
in s

2022-11-30 14:35 UTC, cossartque commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Protections/DistanceProtectionLineSide1LoadBlinder.mo
> +model DistanceProtectionLineSide1LoadBlinder "Simple triangular distance relay, disconnects side 1 of the protected line when the apparent impedance in within a protected zone for longer than a set d
It looks like the only difference is Blinded. We could have a unique model and force Blinded to false in the first case ?

2022-11-30 14:35 UTC, cossartque commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Protections/DistanceProtectionLineSide1LoadBlinder.mo
> +
Pretty much the same comments as in DistanceProtectionLineSide1

2022-11-30 14:36 UTC, cossartque commented on dynawo/sources/Common/Dictionaries/DYNTimeline_en_GB.dic
> +UnderspeedArming          =              Over-speed protection arming
under

2022-11-30 14:36 UTC, cossartque commented on dynawo/sources/Common/Dictionaries/DYNTimeline_en_GB.dic
> +UnderspeedDisarming       =              Over-speed protection disarming
under

2022-11-30 14:36 UTC, cossartque commented on dynawo/sources/Common/Dictionaries/DYNTimeline_en_GB.dic
> +LVRTTripped                =              LVRT generator trip
Is this LVRT automaton implemented here ?

2022-12-15 08:47 UTC, cossartque commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/Protections/OutOfStep.mo
> +model OutOfStep "Out of step protection"
Ok for LossOfSynchronismProtection, thanks!

2022-12-15 08:48 UTC, cossartque commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/Protections/OutOfStep.mo
> +  parameter Types.Angle thetaMinPu "Angle threshold above which the automaton is activated in pu (base omegaNom). It is recommended to use a value that is not to close to (-)pi as the simulator migth
In the other models, we didn't put Pu for rad so I would stick to ThetaMin, thanks!

2022-12-15 08:49 UTC, cossartque commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/Protections/OutOfStep.mo
> +  Types.Angle thetaMonitoredPu "Monitored angle in pu (base omegaNom)";
Not here but this might be done in another PR at some point (to harmonize all the models)

2022-12-15 08:50 UTC, cossartque commented on dynawo/sources/Models/Modelica/PreassembledModels/DistanceProtectionLineSide1.xml
> +    <dyn:unitDynamicModel id="distance" name="Dynawo.Electrical.Controls.Protections.DistanceProtectionLineSide1"/>
Ok, I get it, let's keep it that way

2022-12-15 08:51 UTC, cossartque commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Protections/BaseClasses.mo
> +within Dynawo.Electrical.Controls.Protections;
In Dynawo/Electrical/Controls/Voltage/SecondaryVoltageControl/Simplified/SecondaryVoltageControl_INIT.mo you have an example

2022-12-15 08:52 UTC, cossartque commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Protections/DistanceProtectionLineSide1.mo
> +    if time < 0.1 then  //TODO: clean initialisation, and understand why a filter is needed
Ok, I keep it in mind

2022-12-15 08:52 UTC, cossartque commented on dynawo/sources/Common/Dictionaries/DYNTimeline_en_GB.dic
> +LVRTTripped                =              LVRT generator trip
Ok, thanks

2023-02-07 07:56 UTC, ErwanGuichard49 requested changes

2023-02-07 07:56 UTC, ErwanGuichard49 commented on dynawo/sources/Models/Modelica/PreassembledModels/CMakeLists.txt
> +  UFLS3Steps.xml
3Steps ought to be written before 10Steps

2023-02-07 07:56 UTC, ErwanGuichard49 commented on dynawo/sources/Common/Dictionaries/DYNTimeline_en_GB.dic
> +OOSArming                 =              Out-of-step for generator arming
Pursuant to camel-case convention, I would write OosTripped and OosArming.

2023-02-07 07:56 UTC, ErwanGuichard49 commented on dynawo/sources/Common/Dictionaries/DYNTimeline_en_GB.dic
> +OverspeedTripped          =              Over-speed protection trip
Should the description read as "Overspeed protection tripped" ?

2023-02-07 07:56 UTC, ErwanGuichard49 commented on dynawo/sources/Common/Dictionaries/DYNTimeline_en_GB.dic
> +UnderspeedTripped         =              Under-speed protection trip
Should the description read as "Underspeed protection tripped" ?

2023-02-07 07:56 UTC, ErwanGuichard49 commented on dynawo/sources/Common/Dictionaries/DYNTimeline_en_GB.dic
> +LVRTTripped                =              LVRT generator trip
"LVRT generator tripped" ?

2023-02-07 07:56 UTC, ErwanGuichard49 commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/Protections/LossOfSynchronismProtection.mo
> +  parameter Types.Angle ThetaMin "Angle threshold above which the automaton is activated in rad. It is recommended to use a value that is not to close to (-)pi as the simulator migth skip it.";
It is recommended to use a value not too close to pi or -pi as the simulator might skip it.

2023-02-07 07:56 UTC, ErwanGuichard49 commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/Protections/package.order
> +SpeedProtection
4Points ought to precede 10Points, or am I mistaken ?

2023-02-07 07:56 UTC, ErwanGuichard49 commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Protections/BaseClasses.mo
> +    parameter Types.Time[NbZones] tZone "Time delay of trip in zone i (for each protected zone)";
Time delay of tripping ?

2023-02-07 07:56 UTC, ErwanGuichard49 commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Protections/BaseClasses.mo
> +    Types.Time[NbZones] tThresholdReached(each start = Constants.inf) "Time when enters zone i in s (for each protected zone)";
Time when <what ?> enters zone i

2023-02-07 07:56 UTC, ErwanGuichard49 commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Protections/BaseClasses.mo
> +        tThresholdReached[i] = time;
Two more blank spaces for indentation

2023-02-07 07:56 UTC, ErwanGuichard49 commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Protections/BaseClasses.mo
> +
Please delete this line

2023-02-07 07:56 UTC, ErwanGuichard49 commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Protections/BaseClasses.mo
> +        tThresholdReached[i] = Constants.inf;
Two more blank spaces for indentation

2023-02-07 07:56 UTC, ErwanGuichard49 commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Protections/BaseClasses.mo
> +
Line to be deleted

2023-02-07 07:56 UTC, ErwanGuichard49 commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Protections/BaseClasses.mo
> +
To be deleted ?

2023-02-07 07:56 UTC, ErwanGuichard49 commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Protections/BaseClasses.mo
> +    parameter Types.Time tLagAction "Time-lag due to the actual trip action in s";
tripping action

2023-02-07 07:56 UTC, ErwanGuichard49 commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Protections/BaseClasses.mo
> +    parameter Types.Time tFilter = 0.01 "Time constant of the load change filter in s";
Alphabetical order

2023-02-07 07:56 UTC, ErwanGuichard49 commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Protections/BaseClasses.mo
> +
Line to be deleted ?

2023-02-07 07:56 UTC, ErwanGuichard49 commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Protections/BaseClasses.mo
> +
Line to be deleted ?

2023-02-07 07:56 UTC, ErwanGuichard49 commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Protections/CMakeLists.txt
> +# Copyright (c) 2015-2019, RTE (http://www.rte-france.com)
Should it now become 2023, in every file ?

2023-02-07 08:45 UTC, ErwanGuichard49 commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Protections/BaseClasses.mo
> +        tThresholdReached[i] = time;
You are right, the indentation for lines 60 and 61 should be the same.

2023-02-08 10:40 UTC, ErwanGuichard49 commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/Protections/LossOfSynchronismProtection.mo
> +  parameter Types.Angle ThetaMin "Angle threshold above which the automaton is activated in rad. It is recommended to use a value not to close to pi or -pi as the simulator migth skip it.";
not to close -> not too close

migth -> might

2023-02-08 10:41 UTC, ErwanGuichard49 reviewed
No comment other than on LossOfSynchronismProtection (two typos on line 22)

2023-02-08 10:49 UTC, ErwanGuichard49 approved these changes

2023-02-15 12:07 UTC, cossartque requested changes

2023-02-15 12:07 UTC, cossartque commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Protections/BaseClasses.mo
> +    RealInput PMonitoredPu "Monitored active power in pu (base SnRef)";
input Types.ActivePowerPu

2023-02-15 12:07 UTC, cossartque commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Protections/BaseClasses.mo
> +    RealInput QMonitoredPu "Monitored reactive power in pu (base SnRef)";
input Types.ReactivePowerPu

2023-02-15 12:07 UTC, cossartque commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Protections/BaseClasses.mo
> +    Boolean Blinded "True if the apparent impedance is in the load blinder area";
The coding style is the following : the input variables, one blank line, the output variables, one blank line, the other variables, thanks

2023-02-15 12:07 UTC, cossartque commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Protections/BaseClasses.mo
> +    parameter Types.Time[NbZones] tZone "Time delay for trips in zone i (for each protected zone)";
in s

2023-02-15 12:07 UTC, cossartque commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Protections/BaseClasses.mo
> +    Integer[NbZones] Tripped(each start = 0) "1 if the protection tripped, else 0 (for each protected zone)";
Should be a boolean

2023-02-15 12:07 UTC, cossartque commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Protections/BaseClasses.mo
> +          Tripped[i] = 1;
Boolean

2023-02-15 12:07 UTC, cossartque commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Protections/BaseClasses.mo
> +    when sum(Tripped) >= 1 then
AnyTrue

2023-02-15 12:07 UTC, cossartque commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Protections/BaseClasses.mo
> +    import Modelica.Blocks.Interfaces.RealInput;
Useless

2023-02-15 12:07 UTC, cossartque commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Protections/BaseClasses.mo
> +    RealInput omegaMonitoredPu "Monitored frequency in pu (base omegaNom)";
input Types.AngularVelocityPu

2023-02-15 12:07 UTC, cossartque commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Protections/BaseClasses.mo
> +    parameter Integer NbSteps(min = 1, max = 10) "Number of steps in the UFLS scheme";
Please regroup the parameters

2023-02-15 12:07 UTC, cossartque commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Protections/BaseClasses.mo
> +    Integer[NbSteps] stepActivated(each start = 0) "1 if the ith step of UFLS has been activated, else 0 (for each step of the UFLS scheme)";
Should be a boolean

2023-02-15 12:07 UTC, cossartque commented on dynawo/sources/Models/Modelica/PreassembledModels/UFLS3Steps.xml
> +<?xml version='1.0' encoding='UTF-8'?>
In addition to the comments made, it would be really nice to have dynawo test cases that test all these protections in the nrt folder !

2023-02-15 12:09 UTC, cossartque commented
In addition, could you squash your commits and rebase to the master of dynawo ? Thanks

2023-02-21 12:07 UTC, cossartque requested changes
Not many comments remaining.
Could you add test cases and do the rebase ? Thank you!

2023-02-21 12:07 UTC, cossartque commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/Protections/BaseClasses.mo
> +    when sum(Tripped) >= 1 then
@ErwanGuichard49 haven't we already used anyTrue ?

2023-02-21 12:29 UTC, cossartque commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Protections/BaseClasses.mo
> +    parameter Boolean[NbZones] TrippingZone "True if zone i can send a tripping signal";
Sure, my bad

2023-07-05 07:21 UTC, rosiereflo commented
Hi, would it be possible to rebase this? It would help me testing the latest version of #2797

2023-07-05 08:46 UTC, ErwanGuichard49 commented
> After rebasing, I now get this error
> 
> duplicate Dynawo.Electrical.Machines.OmegaRef.BaseClasses_INIT ( DYNFileSystemUtils.cpp:173 )
> 
> when compiling Modelica models, but I don't see what is duplicated (Omedit also doesn't complain when opening the library)

This may be due to a recent update of the library (https://github.com/dynawo/dynawo/issues/2875), which has split the BaseClasses.mo and BaseClasses_INIT.mo into individual .mo files (one for each model).

2023-07-05 08:57 UTC, ErwanGuichard49 commented
If you want, I can pull the up-to-date non-rebased branch, split the .mo files, and push the properly rebased branch.

2023-07-05 09:08 UTC, ErwanGuichard49 commented
> It's weird because the files seem to be correctly split in the current branch (no more /OmegarRef/BaseClasses.mo, and new dir OmegaRef/BaseClasses/.
> 
> But indeed, I might be easier for you to do it.

If the files are well split, my hypothesis is incorrect.

2023-07-05 09:09 UTC, ErwanGuichard49 commented
> Actually, clean building seems to have fixed the issue

Fine.

2023-07-05 10:16 UTC, rosiereflo commented
> After rebasing, I now get this error
> 
> duplicate Dynawo.Electrical.Machines.OmegaRef.BaseClasses_INIT ( DYNFileSystemUtils.cpp:173 )
> 
> when compiling Modelica models, but I don't see what is duplicated (Omedit also doesn't complain when opening the library)

This might happen when the folders in the Modelica library has been modified, a build without clean might leave some residuals files in the installation that creates this error.
Many thanks for the rebase!

2023-07-10 08:21 UTC, rosiereflo commented
Hi, Could you please let me know if the latest version of the #2797 suits your needs ? Thanks!

2023-07-12 10:53 UTC, rosiereflo commented
> Hello, I did git fetch; git merge upstream/2797_bool_vec; on 14_ProtectionPR (+ added import Modelica.Math.BooleanVectors.index; to Control/Protection/BaseClasses/BaseUFLS.mo), and I now get the following compilation error.
> 
> ```
> [ 25%] �[32mBuilding CXX object CMakeFiles/lib.dir/UFLS3Steps.cpp.o�[0m
> [ 50%] �[32mBuilding CXX object CMakeFiles/lib.dir/UFLS3Steps_Dyn.cpp.o�[0m
> [ 75%] �[32mBuilding CXX object CMakeFiles/lib.dir/UFLS3Steps_Dyn_external.cpp.o�[0m
> In file included from /home/fsabot/Desktop/dynawo_new/install/gcc11/14_ProtectionsPR/Release/shared/dynawo/include/DYNModelManager.h:30,
>                  from /home/fsabot/Desktop/dynawo_new/build/gcc11/14_ProtectionsPR/Release/shared/dynawo/M/M/P/UFLS3Steps/UFLS3Steps_Dyn_external.cpp:2:
> /home/fsabot/Desktop/dynawo_new/build/gcc11/14_ProtectionsPR/Release/shared/dynawo/M/M/P/UFLS3Steps/UFLS3Steps_Dyn_external.cpp: In member function ‘integer_array DYN::ModelUFLS3Steps_Dyn::omc_Modelica_Math_BooleanVectors_index(boolean_array)’:
> /home/fsabot/Desktop/dynawo_new/build/gcc11/14_ProtectionsPR/Release/shared/dynawo/M/M/P/UFLS3Steps/UFLS3Steps_Dyn_external.cpp:101:11: error: call of overloaded ‘integerArrayElementAddress1_(integer_array&, modelica_integer)’ is ambiguous
>   101 |         (*integer_array_element_addr1(&_indices, 1, /* modelica_integer */ (modelica_integer)_count)) = (modelica_integer)_i;
>       |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~
> /home/fsabot/Desktop/dynawo_new/install/gcc11/14_ProtectionsPR/Release/shared/dynawo/include/DYNModelManagerCommon.h:720:19: note: candidate: ‘modelica_integer* DYN::integerArrayElementAddress1_(integer_array&, int)’
>   720 | modelica_integer* integerArrayElementAddress1_(integer_array& source, int dim1);
>       |                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
> /home/fsabot/Desktop/dynawo_new/install/gcc11/14_ProtectionsPR/Release/shared/dynawo/include/DYNModelManagerCommon.h:740:19: note: candidate: ‘modelica_integer* DYN::integerArrayElementAddress1_(integer_array, int)’
>   740 | modelica_integer* integerArrayElementAddress1_(const integer_array source, int dim1);
>       |                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
> gmake[6]: *** [CMakeFiles/lib.dir/build.make:104: CMakeFiles/lib.dir/UFLS3Steps_Dyn_external.cpp.o] Error 1
> gmake[5]: *** [CMakeFiles/Makefile2:83: CMakeFiles/lib.dir/all] Error 2
> gmake[4]: *** [Makefile:91: all] Error 2
> In file included from /home/fsabot/Desktop/dynawo_new/install/gcc11/14_ProtectionsPR/Release/shared/dynawo/include/DYNModelManager.h:30,
>                  from /home/fsabot/Desktop/dynawo_new/build/gcc11/14_ProtectionsPR/Release/shared/dynawo/M/M/P/UFLS3Steps/UFLS3Steps_Dyn_external.cpp:2:
> /home/fsabot/Desktop/dynawo_new/build/gcc11/14_ProtectionsPR/Release/shared/dynawo/M/M/P/UFLS3Steps/UFLS3Steps_Dyn_external.cpp: In member function ‘integer_array DYN::ModelUFLS3Steps_Dyn::omc_Modelica_Math_BooleanVectors_index(boolean_array)’:
> /home/fsabot/Desktop/dynawo_new/build/gcc11/14_ProtectionsPR/Release/shared/dynawo/M/M/P/UFLS3Steps/UFLS3Steps_Dyn_external.cpp:101:11: error: call of overloaded ‘integerArrayElementAddress1_(integer_array&, modelica_integer)’ is ambiguous
>   101 |         (*integer_array_element_addr1(&_indices, 1, /* modelica_integer */ (modelica_integer)_count)) = (modelica_integer)_i;
>       |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~
> /home/fsabot/Desktop/dynawo_new/install/gcc11/14_ProtectionsPR/Release/shared/dynawo/include/DYNModelManagerCommon.h:720:19: note: candidate: ‘modelica_integer* DYN::integerArrayElementAddress1_(integer_array&, int)’
>   720 | modelica_integer* integerArrayElementAddress1_(integer_array& source, int dim1);
>       |                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
> /home/fsabot/Desktop/dynawo_new/install/gcc11/14_ProtectionsPR/Release/shared/dynawo/include/DYNModelManagerCommon.h:740:19: note: candidate: ‘modelica_integer* DYN::integerArrayElementAddress1_(integer_array, int)’
>   740 | modelica_integer* integerArrayElementAddress1_(const integer_array source, int dim1);
>       |                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
> gmake[6]: *** [CMakeFiles/lib.dir/build.make:104: CMakeFiles/lib.dir/UFLS3Steps_Dyn_external.cpp.o] Error 1
> gmake[5]: *** [CMakeFiles/Makefile2:83: CMakeFiles/lib.dir/all] Error 2
> gmake[4]: *** [Makefile:91: all] Error 2
> ```

yes Sorry it was a bad merge on my side. Could you please test it again now?

2023-07-12 12:36 UTC, rosiereflo commented
Ok thanks for the the testcase let me fix this

2023-07-24 08:41 UTC, rosiereflo commented
I just tested the model on OpenModelica and there is also a failure. It seems that this way of using index is not supported

2023-07-24 12:00 UTC, rosiereflo commented
Hi, no it doesn't work. The only way I found that works on OpenModelica is to use a function and to remove the index method:

>     function Sum
>       input Integer NbSteps;
>       input Real[NbSteps] UFLSStep;
>       Real[NbSteps] values;
>       input Boolean[NbSteps] stepActivated;
>       output Real s;
>     algorithm
>       for i in 1:NbSteps loop
>          if stepActivated[i] then
>            values[i] := UFLSStep[i];
>          else
>            values[i] := 0;
>          end if;
>       end for;
>       s := -sum(values);
>     end Sum;

2023-07-24 14:51 UTC, rosiereflo commented
> The above commit works, however, I realise I don't understand how to connect the UFLS model to omegaref. In the attached test case (disconnection of generator 1 (index 0 of omegaref), omegaRef_1_ and omegaRef_grp_0_ do not change during the simulation (frozen after the disconnection I guess), while omegaRef_0_ and omegaRef_grp_1_ are updated (I would have though the opposite). [IEEE14_Fault_UFLS.zip](https://github.com/dynawo/dynawo/files/12146086/IEEE14_Fault_UFLS.zip)

My understanding is that  the connex component index is not modified (only the number of generators belonging to it) so omegaRef_0 is still the variable to use, whereas omega_grp_[0-9] are linked to a specific generator, so the value for the index 0 is not updated anymore as the generator is off, and the others ones are still updated.

2023-09-12 15:36 UTC, ErwanGuichard49 commented
WARNING : the last push by ErwanGuichard49 is a mistake.

Please do not pull this branch as its stands.

2023-10-18 08:57 UTC, joyelfeghali requested changes

2023-10-18 08:57 UTC, joyelfeghali commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/Protections/BaseClasses.mo
The package BaseClasses should be separated from the model BaseLVRT

2023-10-18 08:57 UTC, joyelfeghali commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/Protections/BaseClasses.mo
> +* Copyright (c) 2022, RTE (http://www.rte-france.com)
2023 for copyrights

2023-10-18 08:57 UTC, joyelfeghali commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Protections/BaseClasses.mo
> +    import Modelica;
no need to import Modelica anymore. All essential imports are added in Dynawo package

2023-10-18 08:57 UTC, joyelfeghali commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Protections/BaseClasses.mo
Also here, package should be separated from models

2023-10-19 12:16 UTC, joyelfeghali requested changes

2023-10-19 12:16 UTC, joyelfeghali commented on nrt/data/IEEE14/IEEE14_WithAutomata/IEEE14_UFLS/IEEE14.dyd
> +  <dyn:blackBoxModel id="UFLS" lib="UFLS10Steps" parFile="IEEE14.par" parId="UFLS"/>
same for these blackBoxModels

2023-10-19 12:16 UTC, joyelfeghali commented on nrt/data/IEEE14/cases.py
Could you also add these test cases to the IEEE14_WithAutomata.tex description file?

2023-10-19 12:16 UTC, joyelfeghali commented on nrt/data/IEEE14/IEEE14_WithAutomata/IEEE14_DistanceProtection/IEEE14.dyd
> +  <dyn:blackBoxModel id="DISCONNECT_LINE" lib="EventQuadripoleDisconnection" parFile="IEEE14.par" parId="9"/>
if DISCONNECT_LINE is not used, can we remove it here and in the .par?

Same in all the nrt

2023-10-20 09:11 UTC, joyelfeghali commented on nrt/data/IEEE14/IEEE14_WithAutomata/description/IEEE14_WithAutomata.tex
Only minor corrections are left. Could you also please squash the commits and rebase to the master of dynawo if necessary? Thanks.

2023-10-20 14:26 UTC, merged