#2621 Add a dynawo test case for IEC WT4A
dynawo/dynawo pull request #2626
Opened 2022-12-01 15:45 UTC by GerardThevenon

**Checklist before requesting a review**

*use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes*

- [ ] unit tests and non-regression tests were added (new model, new feature and bug fix)
- [ ] main documentation was updated (update of input/output file, 3rd party, model, repository organization, solver)
- [ ] example documentations were updated (new example in examples folder)
- [ ] if this PR modifies the parameters or inputs/outputs of a model/solver: the corresponding xsl was added in util/xsl and platform DB were updated
- [ ] if this PR modifies a dictionary: the corresponding french dictionary was updated
- [ ] if this commit targets a release branch: the corresponding milestone was added in the ticket and in this PR

2022-12-01 16:25 UTC, cossartque requested changes

2022-12-01 16:25 UTC, cossartque commented on examples/DynaSwing/IEC/Wind/Neplan/WT4ACurrentSource/WT4ACurrentSource.dyd
> +  <dyn:blackBoxModel id="OmegaRefPu" lib="Step" parFile="WT4ACurrentSource.par" parId="OmegaRefPu"/>
Same

2022-12-01 16:25 UTC, cossartque commented on examples/DynaSwing/IEC/Wind/Neplan/WT4ACurrentSource/WT4ACurrentSource.par
> +    <!-- Nominal -->
We should keep in mind to double check all the parameters with the full OM example

2022-12-01 16:25 UTC, cossartque commented on examples/DynaSwing/IEC/Wind/Neplan/WT4ACurrentSource/WT4ACurrentSource.par
> +  <set id="TanPhi">
useless

2022-12-01 16:25 UTC, cossartque commented on examples/DynaSwing/IEC/Wind/Neplan/WT4ACurrentSource/WT4ACurrentSource.par
> +  <set id="OmegaRefPu">
useless

2022-12-02 14:44 UTC, GerardThevenon commented on examples/DynaSwing/IEC/Wind/Neplan/WT4ACurrentSource/WT4ACurrentSource.crv
> +  <curve model="WT4A" variable="WT_wT4Ainjector_theta"/>
Unlike WECC, IEC PLL uses theta.

2022-12-06 08:09 UTC, cossartque commented
Once this test case works, you should add the reference and the test case to the cases.py

2022-12-15 13:03 UTC, cossartque submitted a review, later dismissed

2022-12-15 13:24 UTC, GerardThevenon commented on nrt/data/DynaSwing/cases.py
> +#     IEC Wind Type 4A Current Source     #
Wind Turbine ?

2022-12-15 13:24 UTC, GerardThevenon commented on nrt/data/DynaSwing/cases.py
> +case_description = "IEC - Wind Type 4A - Current source"
Same

2022-12-15 15:13 UTC, cossartque approved these changes

2022-12-15 16:52 UTC, merged