#2616 Adding operating point B, which is stable
dynawo/dynawo pull request #2628
Opened 2022-12-02 15:09 UTC by ErwanGuichard49

closes [2616](https://github.com/dynawo/dynawo/issues/2616)

2022-12-02 15:44 UTC, adriguir reviewed
At first glance, the development seems globally fine and is done in a very nice way. There is only one modification missing: the active power of generator g20 should be decreased by 600 MW to balance the addition of the new g16b generator, which is not the case.
It ends up in a non flat trajectory even without events.

2022-12-05 13:21 UTC, cossartque requested changes

2022-12-05 13:21 UTC, cossartque commented on dynawo/sources/Models/Modelica/Dynawo/Examples/Nordic/Grid/FullDynamicModelB.mo
> +    g15(P0Pu = P0Pu_g15a, Q0Pu = Q0Pu_g15a),
Check gen =

2022-12-05 13:21 UTC, cossartque commented on dynawo/sources/Models/Modelica/Dynawo/Examples/Nordic/Grid/FullDynamicModelB.mo
> +  GeneratorWithControl.GeneratorSynchronousFourWindingsWithControl g15b(P0Pu = P0Pu_g15b, Q0Pu = Q0Pu_g15b, U0Pu = 1.0455, UPhase0 = SIunits.Conversions.from_deg(-52.19), gen = GeneratorWithControl.G
"gen =  " to be checked

2022-12-05 13:21 UTC, cossartque commented on dynawo/sources/Models/Modelica/Dynawo/Examples/Nordic/Grid/FullDynamicModelB.mo
> +  final parameter Types.ActivePowerPu P0Pu_g20b = -1537.4 / Electrical.SystemBase.SnRef;
We should check that this is 600MW less than case A

2022-12-05 13:21 UTC, cossartque commented on dynawo/sources/Models/Modelica/Dynawo/Examples/Nordic/Grid/FullDynamicModelB.mo
> +    g16(P0Pu = P0Pu_g16a, Q0Pu = Q0Pu_g16a),
Modifs on g15 and g18 not necessary

2022-12-05 13:21 UTC, cossartque commented on dynawo/sources/Models/Modelica/Dynawo/Examples/Nordic/Components/GeneratorWithControl/GeneratorParameters.mo
> +  type genFramePreset = enumeration(g01, g02, g03, g04, g05, g06, g07, g08, g09, g10, g11, g12, g13, g14, g15, g15a, g15b, g16, g16b, g17, g18, g18a, g18b, g19, g20) "Generator names";
Modifs on g15 and g18 not necessary

2022-12-05 13:21 UTC, cossartque commented on dynawo/sources/Models/Modelica/Dynawo/Examples/Nordic/Components/GeneratorWithControl/GeneratorParameters.mo
This file should in fact remain the same

2022-12-05 13:21 UTC, cossartque commented on dynawo/sources/Models/Modelica/Dynawo/Examples/Nordic/Grid/FullDynamicModelB.mo
> +    g20(P0Pu = P0Pu_g20b),
This is the only modif that should remain

2022-12-05 13:21 UTC, cossartque commented on dynawo/sources/Models/Modelica/Dynawo/Examples/Nordic/Grid/FullDynamicModelB.mo
> +within Dynawo.Examples.Nordic.Grid;
Please check init

2022-12-06 07:27 UTC, ErwanGuichard49 commented on dynawo/sources/Models/Modelica/Dynawo/Examples/Nordic/Components/GeneratorWithControl/GeneratorParameters.mo
> +  type genFramePreset = enumeration(g01, g02, g03, g04, g05, g06, g07, g08, g09, g10, g11, g12, g13, g14, g15, g15a, g15b, g16, g16b, g17, g18, g18a, g18b, g19, g20) "Generator names";
Modifications canceled

2022-12-06 07:27 UTC, ErwanGuichard49 commented on dynawo/sources/Models/Modelica/Dynawo/Examples/Nordic/Grid/FullDynamicModelB.mo
> +    g16(P0Pu = P0Pu_g16a, Q0Pu = Q0Pu_g16a),
Modifications reversed

2022-12-16 16:46 UTC, closed without merging