#2762 2762 Round time before filling out timeline
dynawo/dynawo pull request #2767
Opened 2023-01-31 16:23 UTC by barondim

**Checklist before requesting a review**

*use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes*

- [ ] unit tests and non-regression tests were added (new model, new feature and bug fix)
- [ ] main documentation was updated (update of input/output file, 3rd party, model, repository organization, solver)
- [ ] example documentations were updated (new example in examples folder)
- [ ] if this PR modifies the parameters or inputs/outputs of a model/solver: the corresponding xsl was added in util/xsl and platform DB were updated
- [ ] if this PR modifies a dictionary: the corresponding french dictionary was updated
- [ ] if this commit targets a release branch: the corresponding milestone was added in the ticket and in this PR

2023-01-31 16:28 UTC, barondim commented
To be merged with https://github.com/dynawo/dynawo-algorithms/pull/326

2023-02-01 08:05 UTC, rosiereflo requested changes

2023-02-02 09:37 UTC, rosiereflo commented on dynawo/sources/API/TL/TLCsvExporter.cpp
> +              << std::setprecision(DYN::getPrecisionAsNbDecimal())
std::fixed and std::setprecision(DYN::getPrecisionAsNbDecimal()) not needed

2023-02-02 10:11 UTC, rosiereflo submitted a review, later dismissed

2023-02-03 07:57 UTC, rosiereflo approved these changes

2023-02-03 07:58 UTC, merged