#2777 IEC Try to remove simulation tricks
dynawo/dynawo pull request #2778
Opened 2023-02-06 14:06 UTC by GerardThevenon

**Checklist before requesting a review**

*use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes*

- [ ] unit tests and non-regression tests were added (new model, new feature and bug fix)
- [ ] main documentation was updated (update of input/output file, 3rd party, model, repository organization, solver)
- [ ] example documentations were updated (new example in examples folder)
- [ ] if this PR modifies the parameters or inputs/outputs of a model/solver: the corresponding xsl was added in util/xsl and platform DB were updated
- [ ] if this PR modifies a dictionary: the corresponding french dictionary was updated
- [ ] if this commit targets a release branch: the corresponding milestone was added in the ticket and in this PR

2023-02-15 12:29 UTC, cossartque requested changes

2023-02-15 12:29 UTC, cossartque commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Sources/IEC/WT4Injector.mo
> -
blank line

2023-02-15 12:29 UTC, cossartque commented on dynawo/sources/Models/Modelica/Dynawo/NonElectrical/Blocks/Complex/ComplexToPolar.mo
> +    len = u.re^2 + u.im^2;
Why not simply 0 ?

2023-02-15 12:43 UTC, cossartque commented on dynawo/sources/Models/Modelica/Dynawo/NonElectrical/Blocks/Complex/ComplexToPolar.mo
> +    len = u.re^2 + u.im^2;
And above, why not sqrt ?

2023-02-16 15:31 UTC, GerardThevenon reviewed
Approved

2023-02-16 17:06 UTC, cossartque approved these changes

2023-02-16 17:06 UTC, merged