#2821 DynaFlow: refactor some models and add timelines
dynawo/dynawo pull request #2874
Opened 2023-04-14 16:34 UTC by cossartque

**Checklist before requesting a review**

*use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes*

- [ ] unit tests and non-regression tests were added (new model, new feature and bug fix)
- [ ] main documentation was updated (update of input/output file, 3rd party, model, repository organization, solver)
- [ ] example documentations were updated (new example in examples folder)
- [ ] the corresponding milestone was added in the ticket and in this PR
- [ ] if this PR modifies the parameters or inputs/outputs of a model/solver: the corresponding xsl was added in util/xsl and platform DB were updated
- [ ] if this PR modifies a dictionary: the corresponding french dictionary was updated

2023-04-17 06:51 UTC, ErwanGuichard49 requested changes
Thanks for the rationalization. A few comments on formal details.

2023-04-17 06:51 UTC, ErwanGuichard49 commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Machines/SignalN/BaseClasses.mo
> +    parameter QStatus qStatus0 "Start voltage regulation status: standard, absorptionMax or generationMax";
Standard, AbsorptionMax, GenerationMax

as in the enumeration on line 143

2023-04-17 06:51 UTC, ErwanGuichard49 commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Machines/SignalN/BaseClasses.mo
>      final parameter Real Alpha = PNom * KGover "Participation of the considered generator in the primary frequency regulation";
Blank line between a parameter and a final parameter ?

2023-04-17 06:51 UTC, ErwanGuichard49 commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Machines/SignalN/BaseClasses.mo
An idea, maybe not for this PR : shouldn't we split these bulky .mo files containing several Modelica models into several files, one for each model ?

This would be more readable, and it is already done that way elsewhere in the libraries.

2023-04-17 06:51 UTC, ErwanGuichard49 commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Machines/SignalN/BaseClasses.mo
>      final parameter Real AlphaSFR = PNom * KSFR "Participation of the considered generator in the secondary frequency regulation";
Blank line ?

2023-04-17 06:51 UTC, ErwanGuichard49 commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Machines/SignalN/BaseClasses_INIT.mo
> +    QStatus qStatus0(start = QStatus.Standard) "Start voltage regulation status: standard, absorptionMax or generationMax";
Standard, AbsorptionMax, GenerationMax

2023-04-17 06:51 UTC, ErwanGuichard49 commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Machines/SignalN/GeneratorPVQNomAltParDiagram_INIT.mo
> +  parameter Types.VoltageModulePu URef0Pu "Start value of the voltage regulation set point in pu (base UNom)";
Blank line between parameter and initial parameter ?

2023-04-17 06:51 UTC, ErwanGuichard49 commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Machines/SignalN/GeneratorPVTfoDiagramPQ_INIT.mo
>    parameter Types.VoltageModulePu URef0Pu "Start value of the voltage regulation set point at terminal in pu (base UNom)";
Initial parameter : to be moved just before the initial variables

2023-04-17 06:51 UTC, ErwanGuichard49 commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/StaticVarCompensators/BaseClasses.mo
> +    final parameter Integer setModeManual0 = Integer(Mode0) "Start value of the mode when in manual configuration";
Blank line ?

2023-04-17 07:23 UTC, cossartque commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Machines/SignalN/BaseClasses.mo
Yes, I create a new issue

2023-04-17 07:29 UTC, ErwanGuichard49 submitted a review, later dismissed

2023-04-20 06:58 UTC, rosiereflo approved these changes

2023-04-24 07:54 UTC, marcochiaramello approved these changes

2023-04-26 12:17 UTC, merged