#2892 Added a generator test case model in Dynawo Examples
dynawo/dynawo pull request #2897
Opened 2023-04-25 13:23 UTC by joyelfeghali

**Checklist before requesting a review**

*use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes*

- [ ] unit tests and non-regression tests were added (new model, new feature and bug fix)
- [ ] main documentation was updated (update of input/output file, 3rd party, model, repository organization, solver)
- [ ] example documentations were updated (new example in examples folder)
- [ ] the corresponding milestone was added in the ticket and in this PR
- [ ] if this PR modifies the parameters or inputs/outputs of a model/solver: the corresponding xsl was added in util/xsl and platform DB were updated
- [ ] if this PR modifies a dictionary: the corresponding french dictionary was updated

2023-04-25 13:28 UTC, rosiereflo commented
Please make sure to update the examples documentation when the testcase is ready :)

2023-05-04 08:04 UTC, cossartque requested changes
A few remarks on the form mainly

2023-05-04 08:04 UTC, cossartque commented on dynawo/sources/Models/Modelica/Dynawo/Examples/Generators/System1Model.mo
> +  Documentation(info = "<html><head></head><body><div><div><div>This test case describes the disconnection of Line1bis from the infinite bus caused by an event. Line1 and Line1bis are connected to an
Maybe we can first describe the test case : two generators, one infinite bus, two lines. The generators use a coordinated voltage control (SignalNQ) that dispatches the needed reactive power between the two generators to control the voltage at the generators connection bus. We simulate the disconnection of a line, bla bla.
We can also say here that SignalN is simply modelled by a step and not a proper regulation, as the infinite bus is here to balance the generation and consumption. Here N is simply used to model an active power reference step.

SignalNQ does not increase the voltage directly, it increases Q, which then results in an increase in the voltage.

2023-05-04 08:04 UTC, cossartque commented on dynawo/sources/Models/Modelica/Dynawo/Examples/Generators/System1Model_INIT.mo
> +  annotation(
One line before annotation and no line after

2023-05-04 08:04 UTC, cossartque commented on dynawo/sources/Models/Modelica/Dynawo/Examples/Generators/System1Model_INIT.mo
> +model System1Model_INIT "Initialisation model for System 1"
Initialisation model is enough (if we give up the System 1 name)

2023-05-04 08:04 UTC, cossartque commented on dynawo/sources/Models/Modelica/Dynawo/Examples/Generators/package.mo
> +package Generators
To be renamed

2023-05-04 08:04 UTC, cossartque commented on dynawo/sources/Models/Modelica/Dynawo/Examples/Generators/package.order
> +System1Model
To be renamed, thanks

2023-05-10 10:18 UTC, cossartque requested changes

2023-05-10 10:18 UTC, cossartque commented on dynawo/sources/Models/Modelica/Dynawo/Examples/DynaFlow/IllustrativeExamples/CoordinatedVControl.mo
> +  import Modelica.ComplexMath;
This line can be deleted

2023-05-10 10:18 UTC, cossartque commented on dynawo/sources/Models/Modelica/Dynawo/Examples/DynaFlow/IllustrativeExamples/CoordinatedVControl.mo
> +  import Dynawo.Electrical;
This line can be deleted

2023-05-10 10:18 UTC, cossartque commented on dynawo/sources/Models/Modelica/Dynawo/Examples/DynaFlow/IllustrativeExamples/CoordinatedVControl.mo
> +equation
You can organize in sections here too.

2023-05-10 10:18 UTC, cossartque commented on dynawo/sources/Models/Modelica/Dynawo/Examples/DynaFlow/IllustrativeExamples/CoordinatedVControl_INIT.mo
> +  extends AdditionalIcons.Init;
import Dynawo needed

2023-05-10 10:18 UTC, cossartque commented on dynawo/sources/Models/Modelica/Dynawo/Examples/DynaFlow/IllustrativeExamples/CoordinatedVControl_INIT.mo
> +  Electrical.Machines.SignalN.GeneratorPQPropDiagramPQ_INIT Generator2(P0Pu = -1.5, PMax = 1000000, PMin = -1000000, Q0Pu = -0.5, QMax0 = 200, QMin0 = -185, U0Pu = 1.05, UPhase0 = 0) annotation(
Dynawo.Electrical

2023-05-15 08:06 UTC, cossartque approved these changes

2023-05-15 10:53 UTC, merged