#2592 DynaFlow: Add HVDC to SVC + Refactoring
dynawo/dynawo pull request #2910
Opened 2023-05-03 10:14 UTC by cossartque

**Checklist before requesting a review**

*use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes*

- [ ] unit tests and non-regression tests were added (new model, new feature and bug fix)
- [ ] main documentation was updated (update of input/output file, 3rd party, model, repository organization, solver)
- [ ] example documentations were updated (new example in examples folder)
- [ ] the corresponding milestone was added in the ticket and in this PR
- [ ] if this PR modifies the parameters or inputs/outputs of a model/solver: the corresponding xsl was added in util/xsl and platform DB were updated
- [ ] if this PR modifies a dictionary: the corresponding french dictionary was updated

2023-05-10 12:44 UTC, ErwanGuichard49 requested changes

2023-05-10 12:44 UTC, ErwanGuichard49 commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/BaseClasses.mo
> +    Types.ReactivePowerPu QInj1PuQNom "Reactive power at terminal 1 in pu (base Q1Nom) (generator convention)";
This is no initial variable, so this line has to be moved between U1RefPu and U1Ref0Pu.

2023-05-10 12:44 UTC, ErwanGuichard49 commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/BaseClasses.mo
> +    Types.ReactivePowerPu QInj2PuQNom "Reactive power at terminal 2 in pu (base Q2Nom) (generator convention)";
This is no initial variable, so this line has to be moved between U2RefPu and U2Ref0Pu.

2023-05-10 12:44 UTC, ErwanGuichard49 commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/BaseClasses.mo
> +    extends BaseClasses.BaseQStatusDangling;
Blank line between import and extends

2023-05-10 12:44 UTC, ErwanGuichard49 commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/BaseClasses.mo
>      extends BaseHvdc(P2Pu(start = s20Pu.re), PInj2Pu(start = - s20Pu.re), Q2Pu(start = s20Pu.im), QInj2Pu(start = - s20Pu.im), terminal2(V(re(start = u20Pu.re), im(start = u20Pu.im)), i(re(start = i2
Blank line between import and extends

2023-05-10 12:44 UTC, ErwanGuichard49 commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/BaseClasses.mo
> +  parameter Types.Angle UPhase10 "Start value of voltage angle and filtered voltage angle at terminal 1 in rad";
Indentation to increase

2023-05-10 12:44 UTC, ErwanGuichard49 commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/BaseClasses_INIT.mo
> +  Types.ReactivePowerPu QInj10PuQNom "Reactive power at terminal 1 in pu (base Q1Nom) (generator convention)";
Swap the lines (alphabetical order) and move them after U1Ref0Pu (an initial parameter).

2023-05-10 14:14 UTC, ErwanGuichard49 commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/BaseClasses.mo
> +    parameter Boolean UseLambda1 = not(Lambda1Pu == 0) "If true, the voltage regulation follows the law U1RefPu = U1Pu + Lambda1Pu * QInj1Pu at terminal 1";
Should it be a final parameter ?

2023-05-10 14:23 UTC, ErwanGuichard49 commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/BaseClasses.mo
> +      Documentation(info = "<html><head></head><body> This HVDC link regulates the active power flowing through itself. The active power reference is given as an input and can be changed during the s
New line for  _end BaseHvdcPFixedReactiveLimits;_

2023-05-10 14:26 UTC, ErwanGuichard49 commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/BaseClasses.mo
> +      Documentation(info = "<html><head></head><body> This HVDC link regulates the active power flowing through itself. The active power reference is given as an input and can be changed during the s
New line for _end BaseHvdcPDanglingFixedReactiveLimits;_

2023-05-10 14:42 UTC, ErwanGuichard49 commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/BaseClasses.mo
> +    parameter Boolean UseLambda2 = not(Lambda2Pu == 0) "If true, the voltage regulation follows the law U2RefPu = U2Pu + Lambda2Pu * QInj2Pu at terminal 2";
Should it be a final parameter ?

2023-05-11 06:58 UTC, rosiereflo submitted a review, later dismissed

2023-05-11 15:32 UTC, ErwanGuichard49 submitted a review, later dismissed

2023-05-12 06:32 UTC, ErwanGuichard49 commented on nrt/data/DynaFlow/cases.py
> +
Please delete this blank line

2023-05-30 10:57 UTC, rosiereflo approved these changes

2023-05-30 10:58 UTC, merged