23 motor loads
dynawo/dynawo pull request #2929
Opened 2023-05-25 10:48 UTC by FredericSabot

This PR adds a fifth order induction motor model and refactors LoadAlphaBetaMotor to allow multiple motors in parallel with a load.

It also adds an electronic load model.

Progresses #2789 

- [ ] unit tests and non-regression tests were added (new model, new feature and bug fix)
- [ ] main documentation was updated (update of input/output file, 3rd party, model, repository organization, solver)
- [ ] example documentations were updated (new example in examples folder)
- [ ] the corresponding milestone was added in the ticket and in this PR
- [ ] if this PR modifies the parameters or inputs/outputs of a model/solver: the corresponding xsl was added in util/xsl and platform DB were updated
- [ ] if this PR modifies a dictionary: the corresponding french dictionary was updated

2023-09-12 15:03 UTC, joyelfeghali requested changes

2023-10-13 12:33 UTC, ErwanGuichard49 commented
> @ErwanGuichard49 Hello, I noticed in your rebase you included a number of changes to the switchoff and generator classes (compared to their current version in the master). Should those be included in this PR or should I remove them?

Hello, you should base your work on the current version of master, the changes that I have brought to your branch ought to be removed.

2023-10-13 12:40 UTC, ErwanGuichard49 commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Basics/SwitchOff/SwitchOffMotor.mo
> +  import Dynawo.Electrical.Constants;
This line can be removed as Dynawo.Electrical.Constants is imported in the _Dynawo.Electrical.Controls.Basics.SwitchOff_ package.

2023-10-13 12:53 UTC, ErwanGuichard49 requested changes

2023-10-13 12:53 UTC, ErwanGuichard49 commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Basics/SwitchOff/package.mo
> -  import Dynawo.Electrical.Constants;
This line has to be restored.

2023-10-13 12:53 UTC, ErwanGuichard49 commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Basics/SwitchOff/SwitchOffDCLine.mo
> +  Connectors.BPin running(value(start = true)) "Indicates if the component is running or not";
Please restore the file as it is on Dynawo master branch.

2023-10-13 12:53 UTC, ErwanGuichard49 commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Basics/SwitchOff/SwitchOffGenerator.mo
> +
Please restore the file as it is on Dynawo master branch.

2023-10-13 12:53 UTC, ErwanGuichard49 commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Basics/SwitchOff/SwitchOffIdealSwitch.mo
> +
Please restore the file as it is on Dynawo master branch.

2023-10-13 12:53 UTC, ErwanGuichard49 commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Basics/SwitchOff/SwitchOffInjector.mo
> +
Please restore the file as it is on Dynawo master branch.

2023-10-13 12:53 UTC, ErwanGuichard49 commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Basics/SwitchOff/SwitchOffLine.mo
> +
Please restore the file as it is on Dynawo master branch.

2023-10-13 12:53 UTC, ErwanGuichard49 commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Basics/SwitchOff/SwitchOffLoad.mo
> +
Please restore the file as it is on Dynawo master branch.

2023-10-13 12:53 UTC, ErwanGuichard49 commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Basics/SwitchOff/SwitchOffLogic.mo
> +  Connectors.BPin running(value(start = true)) "Indicates if the component is running or not";
Please restore the file as it is on Dynawo master branch.

2023-10-13 12:53 UTC, ErwanGuichard49 commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Basics/SwitchOff/SwitchOffLogicSide1.mo
> +  Connectors.BPin runningSide1(value(start = true)) "Indicates if the component is running on side 1 or not";
Please restore the file as it is on Dynawo master branch.

2023-10-13 12:53 UTC, ErwanGuichard49 commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Basics/SwitchOff/SwitchOffLogicSide2.mo
> +  Connectors.BPin runningSide2(value(start = true)) "Indicates if the component is running on side 2 or not";
Please restore the file as it is on Dynawo master branch.

2023-10-13 12:53 UTC, ErwanGuichard49 commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Basics/SwitchOff/SwitchOffShunt.mo
> +
Please restore the file as it is on Dynawo master branch.

2023-10-13 12:53 UTC, ErwanGuichard49 commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Basics/SwitchOff/SwitchOffTransformer.mo
> +
Please restore the file as it is on Dynawo master branch.

2023-10-13 12:53 UTC, ErwanGuichard49 commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Machines/OmegaRef/BaseClasses/BaseGeneratorSimplifiedPFBehavior.mo
> +  Connectors.ImPin omegaRefPu "Network angular reference frequency in pu (base OmegaNom)";
Please restore the file as it is on Dynawo master branch.

2023-10-13 12:53 UTC, ErwanGuichard49 commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Loads/BaseClasses/BaseLoad.mo
> -  extends Dynawo.Electrical.Controls.Basics.SwitchOff.SwitchOffLoad;
Please restore the file as it is on Dynawo master branch.

2023-10-13 12:53 UTC, ErwanGuichard49 commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Machines/BaseClasses/BaseGeneratorSimplified.mo
> +  Connectors.ACPower terminal(V(re(start = u0Pu.re), im(start = u0Pu.im)), i(re(start = i0Pu.re), im(start = i0Pu.im))) "Connector used to connect the synchronous generator to the grid" annotation(
Please restore the file as it is on Dynawo master branch.

2023-10-13 12:53 UTC, ErwanGuichard49 commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Machines/OmegaRef/BaseClasses/BaseGeneratorSynchronous.mo
> +  Connectors.ImPin omegaPu(value(start = SystemBase.omega0Pu)) "Angular frequency in pu";
Please restore the file as it is on Dynawo master branch.

2023-10-13 12:53 UTC, ErwanGuichard49 commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Machines/OmegaRef/BaseClasses_INIT/BaseGeneratorSynchronous_INIT.mo
> +  import Dynawo.Connectors;
Please restore the file as it is on Dynawo master branch.

2023-10-13 12:53 UTC, ErwanGuichard49 commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Machines/OmegaRef/GeneratorSynchronousExt3W_INIT.mo
> +  import Dynawo.Electrical.Machines;
Please restore the file as it is on Dynawo master branch.

2023-10-13 12:53 UTC, ErwanGuichard49 commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Machines/OmegaRef/GeneratorSynchronousExt4W_INIT.mo
> -  extends Dynawo.Electrical.Machines.BaseClasses_INIT.BaseGeneratorParameters_INIT;
Please restore the file as it is on Dynawo master branch.

2023-10-13 12:53 UTC, ErwanGuichard49 commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Machines/OmegaRef/GeneratorSynchronousExtTfo3W_INIT.mo
> +  annotation(preferredView = "text");
Please restore the file as it is on Dynawo master branch.

2023-10-13 12:53 UTC, ErwanGuichard49 commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Machines/OmegaRef/GeneratorSynchronousExtTfo4W_INIT.mo
> +  annotation(preferredView = "text");
Please restore the file as it is on Dynawo master branch.

2023-10-13 12:53 UTC, ErwanGuichard49 commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Machines/SignalN/BaseClasses_INIT/BaseGeneratorSignalNPQDiagram_INIT.mo
> +
Please restore the file as it is on Dynawo master branch.

2023-10-13 12:53 UTC, ErwanGuichard49 commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Machines/SignalN/BaseClasses_INIT/BaseGeneratorSignalN_INIT.mo
> +                              GenerationMax "Reactive power is fixed to its generation limit");
Please restore the file as it is on Dynawo master branch.

2023-10-13 12:53 UTC, ErwanGuichard49 commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Machines/SignalN/GeneratorPVTfoDiagramPQ_INIT.mo
> +
Please restore the file as it is on Dynawo master branch.

2023-10-13 12:53 UTC, ErwanGuichard49 commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Machines/SignalN/GeneratorPVTfo_INIT.mo
> +
Please restore the file as it is on Dynawo master branch.

2023-10-17 08:59 UTC, joyelfeghali commented
> I can quickly add an nrt if needed (based on the Eurostag example 1), although I am not sure where.

You can add the example in dynawo/examples/DynaSwing if it is a DynaSwing test case

2023-10-19 12:26 UTC, joyelfeghali requested changes

2023-10-19 12:26 UTC, joyelfeghali commented on examples/DynaSwing/Eurostag_Example1/Eurostag_LoadAlphaBetaMotorFifthOrder/eurostag.crv
Also add it to the cases.py of nrt/data/DynaSwing

2023-10-30 08:40 UTC, joyelfeghali requested changes
Could you please rebase to the master of Dynawo? Also, a few requested changes from review 1 and review 2 are still left to resolve. Thanks

2023-11-07 08:54 UTC, joyelfeghali commented on examples/DynaSwing/Eurostag_Example1/Eurostag_LoadAlphaBetaMotorFifthOrder/eurostag.crv
The number here is the estimated time of the simulation. We put 1 if it is instantaneous.

2023-11-07 13:18 UTC, joyelfeghali requested changes

2023-11-07 13:18 UTC, joyelfeghali commented on examples/DynaSwing/SingleMachineSystem/SingleMachineSystem_LoadAlphaBetaMotorFifthOrder/SingleMachineSystem.jobs
> +    <dyn:outputs directory="outputs">
<dyn:timeline exportMode="TXT" filter="true"/>

This should be added if not, the timeline.log should be removed

2023-11-07 13:18 UTC, joyelfeghali commented on examples/DynaSwing/SingleMachineSystem/SingleMachineSystem_ElectronicLoad/SingleMachineSystem.jobs
> +    <dyn:outputs directory="outputs">
<dyn:timeline exportMode="TXT" filter="true"/>

This should be added if not, the timeline.log should be removed

2024-05-27 09:05 UTC, joyelfeghali commented on dynawo/sources/Common/Dictionaries/DYNTimeline_en_GB.dic
TimelineKeys.mo file should be updated following this modification. 
You can build dynawo and you will get the modified lines of TimelineKeys.mo

2024-05-28 13:31 UTC, joyelfeghali approved these changes

2024-05-28 14:18 UTC, merged

2024-06-24 13:21 UTC, joyelfeghali commented
Hello @FredericSabot 
We are trying to put in Colib all models that we add in Dynawo library after every development.
If you could add the motor loads to the colib, it would be very helpful since you developed the model. 
I put here the links of the github and the colib page :
https://github.com/CRESYM/colib0.github.io
https://colib.net/index.html

2024-06-26 07:37 UTC, joyelfeghali commented
> Hello, I am currently writing up my thesis, but I can do this towards end of July. What is the expected level of details for the model description?
> 
> FYI, the "how to contribute" link on the Colib git leads to a 404.

It is not urgent, you can do it whenever you can. You can write at least the parameters, equations, and also a link to the Dynawo Modelica model (example of the generator https://colib.net/pages/models/generations/SM1/ )

This is the link to the "how to contribute" page https://colib.net/pages/about/contribute