#2924 Added a PhaseShifterPSign test case
dynawo/dynawo pull request #2930
Opened 2023-05-26 08:10 UTC by joyelfeghali

**Checklist before requesting a review**

*use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes*

- [ ] unit tests and non-regression tests were added (new model, new feature and bug fix)
- [ ] main documentation was updated (update of input/output file, 3rd party, model, repository organization, solver)
- [ ] example documentations were updated (new example in examples folder)
- [ ] the corresponding milestone was added in the ticket and in this PR
- [ ] if this PR modifies the parameters or inputs/outputs of a model/solver: the corresponding xsl was added in util/xsl and platform DB were updated
- [ ] if this PR modifies a dictionary: the corresponding french dictionary was updated

2023-05-30 10:27 UTC, marcochiaramello requested changes

2023-05-30 10:27 UTC, marcochiaramello commented on nrt/data/DynaFlow/PhaseShifterPSign/PhaseShifterPSign.iidm
> +<network xmlns="http://www.itesla_project.eu/schema/iidm/1_0" xmlns:as="http://www.itesla_project.eu/schema/iidm/ext/active-season/1_0" xmlns:bbsp="http://www.itesla_project.eu/schema/iidm/ext/busbar
Please, remove useless iidm extensions

2023-05-30 15:05 UTC, cossartque commented on nrt/data/DynaFlow/PhaseShifterPSign/PhaseShifterPSign.iidm
> +<network xmlns="http://www.itesla_project.eu/schema/iidm/1_0" xmlns:as="http://www.itesla_project.eu/schema/iidm/ext/active-season/1_0" xmlns:bbsp="http://www.itesla_project.eu/schema/iidm/ext/busbar
Done

2023-05-30 15:20 UTC, cossartque requested changes

2023-06-01 09:04 UTC, cossartque commented on nrt/data/DynaFlow/cases.py
> +##############################################################################
Have you checked that this nrt works properly ? Thanks

2023-06-01 09:05 UTC, cossartque approved these changes

2023-06-01 09:43 UTC, cossartque approved these changes

2023-06-01 12:44 UTC, cossartque requested changes

2023-06-01 12:44 UTC, cossartque commented on nrt/data/DynaFlow/PhaseShifterPSign/PhaseShifterPSign.iidm
> +      <phaseTapChanger lowTapPosition="1" tapPosition="13" regulationMode="CURRENT_LIMITER" regulationValue="770" regulating="true">
What we can do is change CURRENT_LIMITER to ACTIVE_POWER_CONTROL, change the regulationValue (i.e the value for PTarget multiplied by 100 to have it in MW)

2023-06-01 12:44 UTC, cossartque commented on nrt/data/DynaFlow/PhaseShifterPSign/PhaseShifterPSign.iidm
> +    <twoWindingsTransformer id="PhaseShifterBis" name="PhaseShifterBis" r="0" x="10" g="0" b="0" ratedU1="400" ratedU2="400" voltageLevelId1="VoltageLevel1" bus1="Bus1" connectableBus1="Bus1" voltage
same

2023-06-01 12:44 UTC, cossartque commented on nrt/data/DynaFlow/PhaseShifterPSign/PhaseShifterPSign.par
> +    <par type="DOUBLE" name="phaseShifter_PTarget" value="0.3"/>
We can try to get the PTarget through the IIDM (of course a dev in the DYNDataInterface is needed)

2023-06-02 12:41 UTC, cossartque reviewed
That is nice work !
Have you checked that all the nrt work ? Thanks

2023-06-02 12:47 UTC, cossartque commented
Also, could you rebase ? Thanks

2023-06-02 15:19 UTC, cossartque submitted a review, later dismissed

2023-06-09 11:36 UTC, cossartque approved these changes

2023-06-09 13:33 UTC, merged