#2970 MachineInfiniteBus in dynawo, examples with appropriate icon an…
dynawo/dynawo pull request #2971
Opened 2023-06-28 14:08 UTC by ErwanGuichard49

closes [#2970](https://github.com/dynawo/dynawo/issues/2970)

2023-06-29 09:52 UTC, cossartque requested changes

2023-06-29 09:52 UTC, cossartque commented on dynawo/sources/Models/Modelica/Dynawo/Examples/SMIB/MachineInfiniteBus.mo
> +  annotation(preferredView = "diagram",
If we put it in dynawo, then we should describe the test case

2023-07-10 11:12 UTC, joyelfeghali requested changes

2023-07-11 11:25 UTC, ErwanGuichard49 commented on dynawo/sources/Models/Modelica/Dynawo/Examples/SMIB/MachineInfiniteBus.mo
> +model MachineInfiniteBus "Synchronous machine infinite bus with constant regulations"
Done

2023-07-12 09:30 UTC, joyelfeghali requested changes

2023-07-12 09:43 UTC, ErwanGuichard49 commented on dynawo/sources/Models/Modelica/Dynawo/Examples/SMIB/SMIBStepEfdPm.mo
> +    experiment(StartTime = 0, StopTime = 30, Tolerance = 0.000001),
Agreed for stopTime = 50 s. The active and reactive load is already mentioned in the documentation, do you want a comment on load.UPu ?

2023-07-12 12:04 UTC, ErwanGuichard49 commented on dynawo/sources/Models/Modelica/Dynawo/Examples/SMIB/SMIBStepEfdPm.mo
> +    experiment(StartTime = 0, StopTime = 30, Tolerance = 0.000001),
I have added a comment to the documentation, saying that P and Q of the load are proportional to the voltage.

2023-07-12 14:11 UTC, joyelfeghali commented on dynawo/sources/Models/Modelica/Dynawo/Examples/SMIB/SMIBStepEfdPm.mo
> +model SMIBStepEfdPm "Synchronous machine infinite bus with steps on Efd and Pm"
Should we change SMIB.Resources.Images.CMakeLists.txt to add the new figures?

2023-07-17 09:17 UTC, merged