#2996 New folders
dynawo/dynawo pull request #2997
Opened 2023-07-07 16:59 UTC by GerardThevenon

**Checklist before requesting a review**

*use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes*

- [ ] unit tests and non-regression tests were added (new model, new feature and bug fix)
- [ ] main documentation was updated (update of input/output file, 3rd party, model, repository organization, solver)
- [ ] example documentations were updated (new example in examples folder)
- [ ] the corresponding milestone was added in the ticket and in this PR
- [ ] if this PR modifies the parameters or inputs/outputs of a model/solver: the corresponding xsl was added in util/xsl and platform DB were updated
- [ ] if this PR modifies a dictionary: the corresponding french dictionary was updated

2023-10-09 07:39 UTC, joyelfeghali requested changes

2023-10-30 15:31 UTC, joyelfeghali requested changes

2023-11-16 16:59 UTC, GerardThevenon commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/WECC/REEC/BaseClasses/BaseREEC.mo
> +  Modelica.Blocks.Interfaces.RealInput QInjRefPu(start = QInj0Pu) "QExt : Reactive power or voltage setpoint at injector in pu (generator convention) (base SNom or UNom)" annotation(
It is for all, but it is specifically written only on the model D diagram

2023-11-16 17:01 UTC, GerardThevenon commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/WECC/REEC/BaseClasses/BaseREEC.mo
> +  Modelica.Blocks.Nonlinear.SlewRateLimiter slewRateLimiter(Falling = DPMin, Rising = DPMax, initType = Modelica.Blocks.Types.Init.InitialState, y_start = PInj0Pu) annotation(
I'm not sure about that (it depends on the simulation time step)

2023-11-16 17:06 UTC, GerardThevenon commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/WECC/REEC/BaseClasses/BaseREEC.mo
> +  Dynawo.NonElectrical.Blocks.Continuous.RateLimFirstOrderFreeze rateLimFirstOrderFreeze(T = tPord, UseFreeze = true, UseRateLim = true, Y0 = PInj0Pu, k = 1) annotation(
Useless indeed

2023-11-16 17:14 UTC, GerardThevenon commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/WECC/BaseControls/CurrentLimitsCalculationC.mo
> +  if SOC >= SOCMax - 1e-5 then
For numerical "safety" (my arbitrary choice)

2023-11-16 17:16 UTC, GerardThevenon commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/WECC/REEC/REECc.mo
> +  Modelica.Blocks.Interfaces.RealInput PGen(start = PInj0Pu) "Generated active power setpoint at injector terminal in pu (base SNom) (generator convention)" annotation(
It should be terminal so the Init is incorrect

2023-11-16 17:33 UTC, GerardThevenon commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/WECC/BaseControls/CurrentLimitsCalculationD.mo
> +  Types.CurrentModulePu iqLimPu = max(min(abs(iqCmdPu), IMaxPu), -IMaxPu);
I need to check deeper

2023-11-16 17:40 UTC, GerardThevenon commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/WECC/REEC/REECd.mo
> +  Modelica.ComplexBlocks.Interfaces.ComplexInput uPu "Complex voltage in pu (base UNom)" annotation(
I guess directly at generator converter

2023-11-24 15:31 UTC, joyelfeghali requested changes

2023-11-24 15:31 UTC, joyelfeghali commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/WECC/BaseControls/CurrentLimitsCalculationA.mo
> +    iqMaxPu = min(iqVdlPu, sqrt(IMaxPu ^ 2 - min(ipLimPu, ipVdlPu) ^ 2));
Follow same changes as #3078 
 min(iqVdlPu, noEvent(if IMaxPu ^ 2 > min(ipLimPu, ipVdlPu) then sqrt(IMaxPu ^ 2 - min(ipLimPu, ipVdlPu) ^ 2) else 0));

2023-11-24 15:31 UTC, joyelfeghali commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/WECC/BaseControls/CurrentLimitsCalculationA.mo
> +      ipMaxPu = min(ipVdlPu, sqrt(IMaxPu ^ 2 - min(iqLimPu, iqVdlPu) ^ 2));
ipMaxPu = min(ipVdlPu, noEvent(if IMaxPu ^ 2 > min(iqLimPu, iqVdlPu) then sqrt(IMaxPu ^ 2 - min(iqLimPu, iqVdlPu) ^ 2) else 0));

2023-11-24 15:31 UTC, joyelfeghali commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/WECC/BaseControls/CurrentLimitsCalculationC.mo
> +    iqMaxPu = min(iqVdlPu, sqrt(IMaxPu ^ 2 - min(ipLimPu, ipVdlPu) ^ 2));
same here for sqrt

2023-11-24 15:31 UTC, joyelfeghali commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/WECC/BaseControls/CurrentLimitsCalculationC.mo
> +        ipMaxPu = min(ipVdlPu, sqrt(IMaxPu ^ 2 - min(iqLimPu, iqVdlPu) ^ 2));
same here for sqrt

2023-11-24 15:31 UTC, joyelfeghali commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/WECC/BaseControls/CurrentLimitsCalculationD.mo
> +      iqMaxPu = min(iqVdlPu, sqrt(IMaxPu ^ 2 - ipCmdPu ^ 2));
same here for sqrt

2023-11-24 15:31 UTC, joyelfeghali commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/WECC/BaseControls/CurrentLimitsCalculationD.mo
> +    ipMaxPu = min(ipVdlPu, sqrt(IMaxPu ^ 2 - iqCmdPu ^ 2));
same here for sqrt

2023-12-11 16:17 UTC, joyelfeghali requested changes

2023-12-13 12:30 UTC, GerardThevenon commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/WECC/REEC/BaseClasses/BaseREEC.mo
> +  Modelica.Blocks.Sources.Constant URefConst(k = if VRef0Pu < 0.5 then UInj0Pu else VRef0Pu) annotation(
I kept it from the previous version _ElectricalControl_

2023-12-13 13:22 UTC, GerardThevenon commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/WECC/REEC/REECa.mo
> +  extends Dynawo.Electrical.Controls.WECC.REEC.BaseClasses.BaseREEC(limiter2.uMax = QMaxPu, limiter2.uMin = QMinPu);
As I showed you, it is an OpenModelica bug. To get around it, you could put the _extends parameters_ before, but then the Icon view and the graphical dimensions will be messed up, although you could copy/paste it from _BaseREEC_.
Another solution is to completely abandon one of two things : the records of parameters or the base model.

2023-12-13 13:25 UTC, GerardThevenon commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/WECC/BaseControls/CurrentLimitsCalculationA.mo
> +    ipMaxFrzPu = pre(ipCmdPu);
I mostly tried to implement what the description of the parameters tHld & tHld2 told.

2023-12-13 13:33 UTC, GerardThevenon commented on dynawo/sources/Models/Modelica/Dynawo/Examples/BESS/WECC/BESSca.mo
I understand that it is only because they are homonyms, which is not ideal indeed, and went out of my radar. For example, REPC and REGC share a time filter constant, so we named them tFilterPC / tFilterGC.

2023-12-13 16:59 UTC, GerardThevenon commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/WECC/REGC/BaseClasses/BaseREGC.mo
> +  Modelica.Blocks.Interfaces.BooleanInput frtOn(start = false) "Boolean signal for iq ramp after fault: true if FRT detected, false otherwise" annotation(
You are right, I forgot to implement a QGen0-dependent logic.
The offDelay signal is only true for a period of time after the fault ends, maybe it is a perfect fit for the CurrentLimitsCalculation issues !

2023-12-14 14:11 UTC, GerardThevenon commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/WECC/BaseControls/CurrentLimitsCalculationA.mo
> +    ipMaxFrzPu = 1;
This is an arbitrary reset number which should not impact the model, no matter its value

2023-12-14 17:49 UTC, GerardThevenon commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/WECC/REGC/BaseClasses/BaseREGC.mo
> +  Modelica.Blocks.Interfaces.BooleanInput frtOn(start = false) "Boolean signal for iq ramp after fault: true if FRT detected, false otherwise" annotation(
I have commited to this idea, therefore I have changed heavily _CurrentLimitsCalculationA_ _IqInjectionLogic_ and _CurrentLimitsCalculationD_
I hope it is objectively simplier

2024-09-24 10:55 UTC, closed without merging