#3005 : Additional pairs for VDL
dynawo/dynawo pull request #3007
Opened 2023-07-17 12:01 UTC by adriguir

**Checklist before requesting a review**

*use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes*

- [ ] unit tests and non-regression tests were added (new model, new feature and bug fix)
- [ ] main documentation was updated (update of input/output file, 3rd party, model, repository organization, solver)
- [ ] example documentations were updated (new example in examples folder)
- [ ] the corresponding milestone was added in the ticket and in this PR
- [ ] if this PR modifies the parameters or inputs/outputs of a model/solver: the corresponding xsl was added in util/xsl and platform DB were updated
- [ ] if this PR modifies a dictionary: the corresponding french dictionary was updated

2023-07-17 12:01 UTC, adriguir commented
There is an associated PR to come on dynawo-rte side

2023-08-03 13:38 UTC, joyelfeghali requested changes
Rebase needed

2023-08-03 13:47 UTC, joyelfeghali requested changes
also need to add the new parameters in the .par of the nrt concerned. 4 of them do not pass (mainly in /dynawo/examples/DynaSwing/GridForming_GridFollowing)

2024-05-16 12:29 UTC, joyelfeghali approved these changes

2024-05-16 12:29 UTC, merged