#2880 Miscellaneous corrections
dynawo/dynawo pull request #3019
Opened 2023-08-07 12:10 UTC by ErwanGuichard49

closes [#2880](https://github.com/dynawo/dynawo/issues/2880)

2023-08-23 12:56 UTC, joyelfeghali requested changes

2023-09-05 06:35 UTC, ErwanGuichard49 commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/IEC/WPP/WPPControl.mo
> +  Dynawo.Electrical.Controls.IEC.BaseControls.WPP.LinearCommunication linearCommunicationWPRef(X0Pu = {-P0Pu * (SystemBase.SnRef / SNom), XWT0Pu}, nu = 2, tLag = tLag, tLead = tLead) annotation(
This was a rebasing error whereby I had kept the original formulation. It has now been reverted to X0Pu.

2023-09-05 07:05 UTC, ErwanGuichard49 commented on dynawo/sources/Models/Modelica/Dynawo/NonElectrical/Blocks/Continuous/VarLimPIDFreeze.mo
>    Blocks.Math.Add3 addI(k2 = -1) annotation(
I have removed the import lines related to Blocks and kept the others, as they shorten the equations.

2023-09-05 08:25 UTC, joyelfeghali requested changes
nrt is OK?

2023-09-05 14:08 UTC, ErwanGuichard49 commented
> nrt is OK?

Yes save for _examples/DynaSwing/IEC/Wind/Neplan/WPP4ACurrentSourceU/WPP4ACurrentSource.jobs_ where the differences were invisible on the graph. It has been updated.

2023-09-12 08:56 UTC, merged