#3117 New block combining rate limiter and limited first order, used …
dynawo/dynawo pull request #3120
Opened 2024-01-22 10:27 UTC by ErwanGuichard49

…in an existing OM test case

**Checklist before requesting a review**

*use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes*

- [ ] unit tests and non-regression tests were added (new model, new feature and bug fix)
- [ ] main documentation was updated (update of input/output file, 3rd party, model, repository organization, solver)
- [ ] example documentations were updated (new example in examples folder)
- [ ] the corresponding milestone was added in the ticket and in this PR
- [ ] if this PR modifies the parameters or inputs/outputs of a model/solver: the corresponding xsl was added in util/xsl and platform DB were updated
- [ ] if this PR modifies a dictionary: the corresponding french dictionary was updated

2024-01-22 12:52 UTC, joyelfeghali requested changes

2024-01-22 12:52 UTC, joyelfeghali commented on dynawo/sources/Models/Modelica/Dynawo/NonElectrical/Blocks/NonLinear/LimRateLimFirstOrder.mo
> +    Documentation(info = "<html><head></head><body><span style=\"font-size: 12px;\">Block to implement a first order filter:</span><div style=\"font-size: 12px;\"><br></div><div style=\"font-size: 12
y/u = 1/(1+s*tS)

tS>0

2024-01-23 08:50 UTC, joyelfeghali requested changes

2024-01-23 08:50 UTC, joyelfeghali commented on dynawo/sources/Models/Modelica/Dynawo/NonElectrical/Blocks/NonLinear/LimRateLimFirstOrder.mo
> +  Modelica.Blocks.Continuous.LimIntegrator limIntegrator(y_start = Y0) annotation(
(outMax = YMax, outMin = YMin)

2024-01-23 08:59 UTC, ErwanGuichard49 commented on dynawo/sources/Models/Modelica/Dynawo/NonElectrical/Blocks/NonLinear/LimRateLimFirstOrder.mo
> +  Modelica.Blocks.Continuous.LimIntegrator limIntegrator(y_start = Y0) annotation(
Corrected

2024-01-23 10:33 UTC, joyelfeghali approved these changes

2024-01-23 10:33 UTC, merged