3049 Assign NaN if either HVDC P or Q equals 0
dynawo/dynawo pull request #3121
Opened 2024-01-22 13:42 UTC by barondim

**Checklist before requesting a review**

*use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes*

- [x] unit tests and non-regression tests were added (new model, new feature and bug fix)
- [ ] main documentation was updated (update of input/output file, 3rd party, model, repository organization, solver)
- [ ] example documentations were updated (new example in examples folder)
- [x] the corresponding milestone was added in the ticket and in this PR
- [ ] if this PR modifies the parameters or inputs/outputs of a model/solver: the corresponding xsl was added in util/xsl and platform DB were updated
- [ ] if this PR modifies a dictionary: the corresponding french dictionary was updated

2024-01-22 14:11 UTC, barondim commented
- [ ] Do not merge ! NRTs do not pass.

2024-01-23 10:19 UTC, rosiereflo requested changes

2024-01-23 10:19 UTC, rosiereflo commented on dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNHvdcLineInterfaceIIDM.cpp
> +      if (connected1) {
It means that if disconnected and the value is not 0 then the assigment is not done

2024-01-23 15:57 UTC, barondim commented
- [ ] To be merged with https://github.com/dynawo/dynaflow-launcher/pull/723

2024-01-24 14:25 UTC, rosiereflo approved these changes

2024-01-24 16:03 UTC, merged