#3136 Add hasInitialConditions_ member to DataInterface
dynawo/dynawo pull request #3143
Opened 2024-02-21 15:03 UTC by gaouizer

**Checklist before requesting a review**

*use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes*

- [x] unit tests and non-regression tests were added (new model, new feature and bug fix)
- [ ] main documentation was updated (update of input/output file, 3rd party, model, repository organization, solver)
- [ ] example documentations were updated (new example in examples folder)
- [x] the corresponding milestone was added in the ticket and in this PR
- [ ] if this PR modifies the parameters or inputs/outputs of a model/solver: the corresponding xsl was added in util/xsl and platform DB were updated
- [ ] if this PR modifies a dictionary: the corresponding french dictionary was updated

2024-02-21 15:47 UTC, marcochiaramello requested changes

2024-02-21 15:47 UTC, marcochiaramello commented on dynawo/sources/Modeler/DataInterface/DYNComponentInterface.h
> +   * @param hasInitialConditions @b true is component has initial conditions set, @b false else
true if

2024-02-21 15:47 UTC, marcochiaramello commented on dynawo/sources/Modeler/DataInterface/DYNComponentInterface.h
> +   * @return  @b true is component has initial conditions set, @b false else
true if

2024-02-21 15:47 UTC, marcochiaramello commented on dynawo/sources/Modeler/DataInterface/DYNComponentInterface.h
> +  bool hasInitialConditions_;  ///< @b true is component has initial conditions set, @b false else
true if

2024-02-21 15:47 UTC, marcochiaramello commented on dynawo/sources/Modeler/DataInterface/PowSyblIIDM/test/TestGeneratorInterface.cpp
> +  ASSERT_FALSE(genItf.hasInitialConditions());
I'd try as much as possible to test the hasInitialConditions setting P,Q,V,angle (it depends on the component) via myComponent.getTerminal().setBlaBla

2024-02-26 13:10 UTC, rosiereflo requested changes

2024-02-27 11:55 UTC, marcochiaramello approved these changes

2024-02-27 11:59 UTC, rosiereflo approved these changes

2024-02-27 11:59 UTC, rosiereflo commented
Could you please squash the commits?

2024-02-28 08:51 UTC, merged