#3091 Pss1a, Pss2a and other necessary models
dynawo/dynawo pull request #3149
Opened 2024-02-28 16:58 UTC by ErwanGuichard49

**Checklist before requesting a review**

*use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes*

- [ ] unit tests and non-regression tests were added (new model, new feature and bug fix)
- [ ] main documentation was updated (update of input/output file, 3rd party, model, repository organization, solver)
- [ ] example documentations were updated (new example in examples folder)
- [ ] the corresponding milestone was added in the ticket and in this PR
- [ ] if this PR modifies the parameters or inputs/outputs of a model/solver: the corresponding xsl was added in util/xsl and platform DB were updated
- [ ] if this PR modifies a dictionary: the corresponding french dictionary was updated

2024-02-29 12:19 UTC, joyelfeghali requested changes

2024-02-29 12:19 UTC, joyelfeghali commented on nrt/data/SMIB/Standard/TestCase1ST4B/reference/outputsTestCase1ST4B/curves/curves.csv
nrt fails for this test case. We have to modify it when we add st4b, there is no modification of PssIEEE2B

2024-02-29 12:19 UTC, joyelfeghali commented on nrt/data/SMIB/Standard/TestCase3ST4B/reference/outputsTestCase3ST4B/curves/curves.csv
same for this nrt

2024-02-29 13:20 UTC, ErwanGuichard49 commented on dynawo/sources/Models/Modelica/Dynawo/NonElectrical/Blocks/Continuous/LeadMOrderLag.mo
> +  parameter Integer MMax = 6 "Maximum lag order";
We need a fixed number of first order filters known before compilation, hence the parameter MMax.

2024-02-29 13:21 UTC, ErwanGuichard49 commented on dynawo/sources/Models/Modelica/Dynawo/NonElectrical/Blocks/Continuous/LeadMOrderLag.mo
> +  for i in 1:MMax-2 loop
It is assumed that MMax is at least 3. I can write it somewhere.

2024-02-29 13:27 UTC, ErwanGuichard49 commented on nrt/data/SMIB/Standard/TestCase1ST4B/reference/outputsTestCase1ST4B/curves/curves.csv
Strangely, the nrt was successful on my computer.

2024-02-29 13:27 UTC, ErwanGuichard49 commented on nrt/data/SMIB/Standard/TestCase3ST4B/reference/outputsTestCase3ST4B/curves/curves.csv
Successful on my computer.

2024-02-29 13:39 UTC, joyelfeghali commented on nrt/data/SMIB/Standard/TestCase1ST4B/reference/outputsTestCase1ST4B/curves/curves.csv
Why the LeadMOrderLag would give different values?

2024-02-29 13:52 UTC, ErwanGuichard49 commented on dynawo/sources/Models/Modelica/Dynawo/NonElectrical/Blocks/Continuous/RampTrackingFilter.mo
> +  parameter Integer N "Order";
Indeed, the default value is overridden by the value set in the .par file. I have restored the default values for M and N.

2024-02-29 14:04 UTC, ErwanGuichard49 commented on dynawo/sources/Models/Modelica/Dynawo/NonElectrical/Blocks/Continuous/LeadMOrderLag.mo
> +  for i in 1:MMax-2 loop
Another possibility is to turn MMax and NMax into final parameters, as their value is fixed from the compilation and thus cannot be changed with the .par file. The only way to increase MMax and NMax is to change the value in the .mo file and to recompile.

2024-03-01 10:04 UTC, ErwanGuichard49 commented on dynawo/sources/Models/Modelica/PreassembledModels/GeneratorSynchronousFourWindingsTGov1SexsPss2A.xml
> +    <dyn:unitDynamicModel id="pss" name="Dynawo.Electrical.Controls.Machines.PowerSystemStabilizers.Standard.PSS2A1" initName="Dynawo.Electrical.Controls.Machines.PowerSystemStabilizers.BaseClasses_I
Done

2024-03-04 08:27 UTC, joyelfeghali approved these changes

2024-03-04 08:27 UTC, merged