#3091 HyGov, TGov, IEEEX2
dynawo/dynawo pull request #3150
Opened 2024-03-04 12:15 UTC by ErwanGuichard49

**Checklist before requesting a review**

*use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes*

- [ ] unit tests and non-regression tests were added (new model, new feature and bug fix)
- [ ] main documentation was updated (update of input/output file, 3rd party, model, repository organization, solver)
- [ ] example documentations were updated (new example in examples folder)
- [ ] the corresponding milestone was added in the ticket and in this PR
- [ ] if this PR modifies the parameters or inputs/outputs of a model/solver: the corresponding xsl was added in util/xsl and platform DB were updated
- [ ] if this PR modifies a dictionary: the corresponding french dictionary was updated

2024-03-06 09:53 UTC, joyelfeghali requested changes

2024-03-06 10:31 UTC, ErwanGuichard49 commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/Governors/Standard/Steam/TGov3.mo
> +  parameter Types.PerUnit K2 "Fraction of IP shaft power after first boiler pass";
Indeed

2024-03-06 10:39 UTC, ErwanGuichard49 commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/Governors/Standard/Hydraulic/HyGov.mo
> +  Modelica.Blocks.Nonlinear.Limiter limiter(uMax = OpeningGateMax, uMin = OpeningGateMin) annotation(
Of course, the LimitedPI block is enough.

2024-03-08 13:12 UTC, joyelfeghali requested changes

2024-03-08 15:01 UTC, joyelfeghali approved these changes

2024-03-08 15:02 UTC, merged