#3042 Add Timeline to SVC model
dynawo/dynawo pull request #3175
Opened 2024-03-20 12:55 UTC by joyelfeghali

**Checklist before requesting a review**

*use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes*

- [x] unit tests and non-regression tests were added (new model, new feature and bug fix)
- [ ] main documentation was updated (update of input/output file, 3rd party, model, repository organization, solver)
- [ ] example documentations were updated (new example in examples folder)
- [x] the corresponding milestone was added in the ticket and in this PR
- [ ] if this PR modifies the parameters or inputs/outputs of a model/solver: the corresponding xsl was added in util/xsl and platform DB were updated
- [x] if this PR modifies a dictionary: the corresponding french dictionary was updated

2024-03-20 13:07 UTC, joyelfeghali commented
The solver used here for the nrt is IDA (we got the results we expected), note that when using the SIM solver the results are different (sampling every 20 s instead of 10 s). This is a temporary implementation until #3163 is solved.
tSample = 10 s is the default value, maxStep should be <= tSample.

2024-03-25 13:07 UTC, rosiereflo requested changes

2024-03-25 13:07 UTC, rosiereflo commented on nrt/data/DynaFlow/GeneratorPVTfoSVRTimeline/GeneratorPVTfoSVRTimeline.crv
> +    Copyright (c) 2023, RTE (http://www.rte-france.com)
2024

2024-03-25 14:28 UTC, rosiereflo approved these changes

2024-03-25 15:16 UTC, merged