#3191 Phase and Ratio Tap Changer transfortmer OM Models introduction…
dynawo/dynawo pull request #3218
Opened 2024-05-15 15:08 UTC by gaouizer

… with examples and nrts

**Checklist before requesting a review**

*use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes*

- [x] unit tests and non-regression tests were added (new model, new feature and bug fix)
- [ ] main documentation was updated (update of input/output file, 3rd party, model, repository organization, solver)
- [x] example documentations were updated (new example in examples folder)
- [x] the corresponding milestone was added in the ticket and in this PR
- [ ] if this PR modifies the parameters or inputs/outputs of a model/solver: the corresponding xsl was added in util/xsl and platform DB were updated
- [ ] if this PR modifies a dictionary: the corresponding french dictionary was updated

2024-05-15 15:16 UTC, rosiereflo commented
references of the nrt are missing

2024-05-22 09:38 UTC, joyelfeghali requested changes

2024-05-22 09:38 UTC, joyelfeghali commented on dynawo/sources/Models/Modelica/Dynawo/Examples/DynaFlow/IllustrativeExamples/PhaseShifterTransformer.mo
> +  Dynawo.Electrical.Buses.InfiniteBus gen_01(UPu = U0Pu_gen_01, UPhase = 0) annotation(
Could you also remove the "_" from the components name ?
gen1
load1
bus1
bus2
bus3
PhaseShifter1 instead of shift_controller_01
...

2024-05-22 09:38 UTC, joyelfeghali commented on dynawo/sources/Models/Modelica/Dynawo/Examples/DynaFlow/IllustrativeExamples/PhaseShifterTransformer.mo
> +    __OpenModelica_simulationFlags(ls = "klu", lv = "LOG_STATS", nls = "kinsol", s = "euler"),Documentation(info = "<html><head></head><body><div>This test case is composed one infinite bus, three re
You could also add a figure to the description

2024-05-22 09:38 UTC, joyelfeghali commented on dynawo/sources/Models/Modelica/Dynawo/Examples/DynaFlow/IllustrativeExamples/PhaseShifterTransformer.mo
> +  Dynawo.Electrical.Controls.Transformers.PhaseShifterP shift_controller_01(P0 = 0.7, PDeadBand = 0.05, PTarget = 0.7, state0 = Dynawo.Electrical.Controls.Transformers.BaseClasses.TapChangerPhaseShif
tapMin = 1 and tapMax = 19

2024-05-22 09:38 UTC, joyelfeghali commented on dynawo/sources/Models/Modelica/Dynawo/Examples/DynaFlow/IllustrativeExamples/PhaseShifterTransformer.mo
> +    tfo_01.tap.value = shift_controller_01.tap.value;
tfo_01.tap.value is different than the shift_controller_01.tap.value at the end 
tfo_01.tap.value have the correct value but  shift_controller_01.tap.value doesn't seem to updated

2024-05-30 15:17 UTC, joyelfeghali commented on dynawo/sources/Models/Modelica/Dynawo/Examples/DynaFlow/IllustrativeExamples/PhaseShifterTransformer.mo
> +    tfo_01.tap.value = shift_controller_01.tap.value;
Issue opened : #3246

2024-05-31 07:31 UTC, joyelfeghali approved these changes

2024-05-31 08:06 UTC, merged