#3270 Use vectors instead of all pointers.
dynawo/dynawo pull request #3271
Opened 2024-06-10 12:36 UTC by gautierbureau

**Checklist before requesting a review**

*use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes*

- [ ] unit tests and non-regression tests were added (new model, new feature and bug fix)
- [ ] main documentation was updated (update of input/output file, 3rd party, model, repository organization, solver)
- [ ] example documentations were updated (new example in examples folder)
- [ ] the corresponding milestone was added in the ticket and in this PR
- [ ] if this PR modifies the parameters or inputs/outputs of a model/solver: the corresponding xsl was added in util/xsl and platform DB were updated
- [ ] if this PR modifies a dictionary: the corresponding french dictionary was updated

2024-06-20 07:36 UTC, rosiereflo requested changes
Are all the nrts passing? (public and private) thanks

2024-06-20 07:36 UTC, rosiereflo commented on dynawo/sources/Modeler/Common/DYNModelMulti.cpp
> +  std::fill(fLocal_.begin(), fLocal_.end(), 0.);
not equivalent to the existing line

2024-07-02 12:33 UTC, gautierbureau commented
> Are all the nrts passing? (public and private) thanks

Yes https://github.com/dynawo/dynawo/actions/runs/9756508428

2024-07-02 13:04 UTC, rosiereflo approved these changes

2024-07-03 06:43 UTC, merged