#3224 OEL, UEL, SCL models and test cases
dynawo/dynawo pull request #3300
Opened 2024-06-26 10:10 UTC by ErwanGuichard49

closes [#3224 ]

2024-08-14 15:46 UTC, joyelfeghali requested changes

2024-08-14 15:46 UTC, joyelfeghali commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/StatorCurrentLimiters/Standard/BaseClasses/SclOelActivation.mo
> +  parameter Types.PerUnit IThOff "OEL reset threshold value";
SCL reset threshold value

2024-08-14 15:46 UTC, joyelfeghali commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/StatorCurrentLimiters/Standard/BaseClasses/SclOelActivation.mo
> +  parameter Types.Time tEnOel "OEL activation delay time in s";
Overexcited activation delay time in s

2024-08-14 15:46 UTC, joyelfeghali commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/StatorCurrentLimiters/Standard/BaseClasses/SclOelActivation.mo
> +  parameter Types.Time tOff "OEL reset delay time in s";
SCL...

2024-08-14 15:46 UTC, joyelfeghali commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/StatorCurrentLimiters/Standard/BaseClasses/SclOelActivation.mo
> +  Modelica.Blocks.Interfaces.RealInput IOelAct(start = 0) "Input signal" annotation(
"SCL OEL current actual value"

2024-08-14 15:46 UTC, joyelfeghali commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/StatorCurrentLimiters/Standard/BaseClasses/SclOelActivation.mo
> +  Modelica.Blocks.Interfaces.RealInput IOelRef(start = IOelRef0Pu) "Input signal" annotation(
"SCL OEL reference value"

2024-08-14 15:46 UTC, joyelfeghali commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/StatorCurrentLimiters/Standard/BaseClasses/SclOelActivation.mo
> +  Modelica.Blocks.Interfaces.RealInput tErr(start = 0) "Input signal" annotation(
"SCL timer error"

2024-08-14 15:46 UTC, joyelfeghali commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/StatorCurrentLimiters/Standard/BaseClasses/SclOelActivation.mo
> +  Modelica.Blocks.Interfaces.RealInput VtFiltPu(start = Vt0Pu) "Input voltage" annotation(
"Filtered stator voltage in pu (UNom)"

2024-08-14 15:46 UTC, joyelfeghali commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/StatorCurrentLimiters/Standard/BaseClasses/SclOelActivation.mo
> +  parameter Types.Time tErr0;
"SCL timer error initial value"

2024-08-14 15:46 UTC, joyelfeghali commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/StatorCurrentLimiters/Standard/BaseClasses/SclOelActivation.mo
> +  parameter Types.VoltageModulePu Vt0Pu "Initial input voltage";
in pu (base UNom)

2024-08-14 15:46 UTC, joyelfeghali commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/StatorCurrentLimiters/Standard/BaseClasses/SclOelActivation.mo
> +model SclOelActivation
"IBias calculation for Scl2c"

2024-08-14 15:46 UTC, joyelfeghali commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/StatorCurrentLimiters/Standard/BaseClasses/SclOelActivation.mo
> +  end when;
if instead of a when and IOelRef ==IInst

2024-08-14 15:46 UTC, joyelfeghali commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/StatorCurrentLimiters/Standard/BaseClasses/SclReferenceCurrent.mo
> +model SclReferenceCurrent
"IRef calculation for Scl2c"

2024-08-14 15:46 UTC, joyelfeghali commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/StatorCurrentLimiters/Standard/BaseClasses/SclReferenceCurrent.mo
> +  Modelica.Blocks.Interfaces.RealOutput IRefPu(start = 0) "Reference current" annotation(
start = IRef0Pu

2024-08-14 15:46 UTC, joyelfeghali commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/StatorCurrentLimiters/Standard/BaseClasses/SclReferenceCurrent.mo
> +  Modelica.Blocks.Interfaces.RealOutput tErr(start = tErr0) annotation(
"SCL timer error"

2024-08-14 15:46 UTC, joyelfeghali commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/StatorCurrentLimiters/Standard/BaseClasses/SclReferenceCurrent.mo
> +  Modelica.Blocks.Interfaces.RealInput VtFiltPu(start = Vt0Pu) "Input voltage" annotation(
"Filtered stator voltage in pu (UNom)"

2024-08-14 15:46 UTC, joyelfeghali commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/StatorCurrentLimiters/Standard/BaseClasses/SclReferenceCurrent.mo
> +  parameter Types.Time tErr0;
"SCL timer error initial value"

2024-08-14 15:46 UTC, joyelfeghali commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/StatorCurrentLimiters/Standard/BaseClasses/SclReferenceCurrent.mo
> +  parameter Types.VoltageModulePu Vt0Pu "Initial input voltage";
in pu (base UNom)

2024-08-14 15:46 UTC, joyelfeghali commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/StatorCurrentLimiters/Standard/BaseClasses/SclUelActivation.mo
> +  parameter Types.PerUnit IInst "OEL instantaneous field current limit";
IInstUel
it is different than IInst

2024-08-14 15:46 UTC, joyelfeghali commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/StatorCurrentLimiters/Standard/BaseClasses/SclUelActivation.mo
> +  parameter Types.PerUnit IInst "OEL instantaneous field current limit";
"Underexcited region instantaneous stator current limit"

2024-08-14 15:46 UTC, joyelfeghali commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/StatorCurrentLimiters/Standard/BaseClasses/SclUelActivation.mo
> +model SclUelActivation
"IUelbias calculation for Scl2c"

2024-08-14 15:46 UTC, joyelfeghali commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/StatorCurrentLimiters/Standard/BaseClasses/SclUelActivation.mo
> +  parameter Types.PerUnit IThOff "OEL reset threshold value";
"SCL reset..."

2024-08-14 15:46 UTC, joyelfeghali commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/StatorCurrentLimiters/Standard/BaseClasses/SclUelActivation.mo
> +  parameter Types.PerUnit IUelReset "OEL reset-reference, if OEL is inactive";
IReset

"SCL reset-reference, if inactive"

2024-08-14 15:46 UTC, joyelfeghali commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/StatorCurrentLimiters/Standard/BaseClasses/SclUelActivation.mo
> +  parameter Types.Time tEnUel "OEL activation delay time in s";
Underexcited activation delay time

2024-08-14 15:46 UTC, joyelfeghali commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/StatorCurrentLimiters/Standard/BaseClasses/SclUelActivation.mo
> +  parameter Types.Time tOff "OEL reset delay time in s";
SCL

2024-08-14 15:46 UTC, joyelfeghali commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/StatorCurrentLimiters/Standard/BaseClasses/SclUelActivation.mo
> +  Modelica.Blocks.Interfaces.RealInput IUelAct(start = 0) "Input signal" annotation(
"SCL UEL current actual value"

2024-08-14 15:46 UTC, joyelfeghali commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/StatorCurrentLimiters/Standard/BaseClasses/SclUelActivation.mo
> +  Modelica.Blocks.Interfaces.RealInput IUelRef(start = IUelRef0Pu) "Input signal" annotation(
"SCL UEL reference value"

2024-08-14 15:46 UTC, joyelfeghali commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/StatorCurrentLimiters/Standard/BaseClasses/SclUelActivation.mo
> +  Modelica.Blocks.Interfaces.RealInput tErr(start = tErr0) "Input signal" annotation(
"SCL timer error"

2024-08-14 15:46 UTC, joyelfeghali commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/StatorCurrentLimiters/Standard/BaseClasses/SclOelActivation.mo
> +  Modelica.Blocks.Interfaces.RealInput IOelAct(start = 0) "Input signal" annotation(
intialized at IOelRef0Pu

2024-08-14 15:46 UTC, joyelfeghali commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/StatorCurrentLimiters/Standard/BaseClasses/SclUelActivation.mo
> +  Modelica.Blocks.Interfaces.RealInput IUelAct(start = 0) "Input signal" annotation(
initialized at IUELRef0Pu

2024-08-14 15:46 UTC, joyelfeghali commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/StatorCurrentLimiters/Standard/BaseClasses/SclUelActivation.mo
> +  parameter Types.Time tErr0;
"SCL timer error"

2024-08-14 15:46 UTC, joyelfeghali commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/StatorCurrentLimiters/Standard/BaseClasses/SclUelActivation.mo
> +  end when;
if instead of when

2024-08-14 15:46 UTC, joyelfeghali commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/StatorCurrentLimiters/Standard/Scl2c.mo
> +  Modelica.ComplexBlocks.Interfaces.ComplexInput itPu(re(start = it0Pu.re), im(start = it0Pu.im)) "Complex stator current in pu (base UNom)" annotation(
base SnRef, UNom

2024-08-14 15:46 UTC, joyelfeghali commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/StatorCurrentLimiters/Standard/Scl1c_INIT.mo
> +  Types.ComplexCurrentPu it0Pu "Initial complex stator current in pu (base SNom, UNom)";
base SnRef, UNom

2024-08-14 15:46 UTC, joyelfeghali commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/StatorCurrentLimiters/Standard/Scl2c.mo
> +  parameter Types.ComplexCurrentPu it0Pu "Initial complex stator current in pu (base SNom, UNom)";
base SnRef, UNom

2024-08-14 15:46 UTC, joyelfeghali commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/UnderExcitationLimiters/Standard/Uel1.mo
> +  parameter Types.ComplexCurrentPu it0Pu "Initial complex stator current in pu (base SNom, UNom)";
base SnRef, UNom

2024-08-14 15:46 UTC, joyelfeghali commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/UnderExcitationLimiters/Standard/Uel1_INIT.mo
> +  Types.ComplexCurrentPu it0Pu "Initial complex stator current in pu (base SNom, UNom)";
base SnRef, UNom

2024-08-19 07:04 UTC, ErwanGuichard49 commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/OverExcitationLimiters/Standard/BaseClasses/OelActivation.mo
> +  elsewhen IRefPu >= IInst and timer1.y > tOff then
Indeed, I have replaced >= by ==

2024-08-19 07:27 UTC, ErwanGuichard49 commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/OverExcitationLimiters/Standard/Oel2c.mo
> +  Modelica.Blocks.Continuous.FirstOrder firstOrder(T = tROel, k = KScale, y_start = KScale * Input0Pu) annotation(
Done

2024-08-19 07:43 UTC, ErwanGuichard49 commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/OverExcitationLimiters/Standard/Oel3c.mo
> +  final parameter Types.PerUnit KScale = ITfPu / Input0Pu "OEL input signal scaling factor";
The calculation of KScale guarantees a zero input for the limited integrator. The 2016 IEEE documentation gives no value for KSCale but indicates that it has to match the ITfPu pu base value.

2024-08-19 07:52 UTC, ErwanGuichard49 commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/OverExcitationLimiters/Standard/Oel5c.mo
> +  Modelica.Blocks.Math.Add3 add3(k3 = -1) annotation(
k1 = -1, k3 = -1

2024-08-19 08:04 UTC, ErwanGuichard49 commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/OverExcitationLimiters/Standard/Oel5c.mo
> +  connect(greaterThreshold2.y, switch2.u2) annotation(
Of course. If flipFlopS.y = true, switch2.y = IfdRef2Pu. If flipFlopS.y = false, switch2.y = IfdRef1Pu.

2024-08-19 08:07 UTC, ErwanGuichard49 commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/OverExcitationLimiters/Standard/Oel5c.mo
> +  Modelica.Blocks.Logical.LessEqualThreshold lessEqualThreshold annotation(
As the limited integrator output has a zero lower limit, a LessEqualThreshold block fulfills the necessary task.

2024-08-19 08:10 UTC, ErwanGuichard49 commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/OverExcitationLimiters/Standard/BaseClasses/OelActivation.mo
> +  end when;
The 2016 documentation describes an if structure. However, there is no third branch if both logical tests fail.

2024-08-19 08:41 UTC, ErwanGuichard49 commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/OverExcitationLimiters/Standard/Oel5c.mo
> +  final parameter Types.PerUnit KScale2 = if Vfe0Pu > 0 then VfeRefPu / Vfe0Pu else 0 "Scale factor for exciter field current";
I have redefined them as non final parameters. The calculations were aimed at ensuring integrator inputs equal to zero.

2024-08-19 08:53 UTC, ErwanGuichard49 commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/VoltageRegulators/Standard/St7c.mo
> +  connect(min1.yMin, VFbPu) annotation(
Yes

2024-08-19 09:00 UTC, ErwanGuichard49 commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/VoltageRegulators/Standard/St7c_INIT.mo
> +  UsRef0Pu = (1 + Kia) * Efd0Pu / Kpa + Us0Pu;
UsRef0Pu has been redefined as a non final parameter. The goal is to transmit the value of UsRef0Pu between St7c and Uel2c.

2024-08-19 09:12 UTC, ErwanGuichard49 commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/StatorCurrentLimiters/Standard/Scl1c.mo
> +  parameter Types.VoltageModulePu VSclDb "Dead-band for reactive power or power factor in pu (base SnRef)";
It should be Types.ReactivePowerPu as VSclDb is compared to the reactive power output of the generator.

2024-08-19 09:25 UTC, ErwanGuichard49 commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/StatorCurrentLimiters/Standard/BaseClasses/SclReferenceCurrent.mo
> +  Modelica.Blocks.Logical.And and1 annotation(
Indeed

2024-08-19 13:13 UTC, ErwanGuichard49 commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/StatorCurrentLimiters/Standard/BaseClasses/SclUelActivation.mo
> +  parameter Types.PerUnit IInst "OEL instantaneous field current limit";
Yes

2024-08-19 13:15 UTC, ErwanGuichard49 commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/OverExcitationLimiters/Standard/BaseClasses/OelActivation.mo
> +  end when;
I have added an else branch, leading to IBias = 0.

2024-09-25 15:19 UTC, joyelfeghali commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/StatorCurrentLimiters/Standard/BaseClasses/SclOelActivation.mo
> +  parameter Types.VoltageModulePu VtResetPu "SCL voltage reset value in pu (base UNom)";
"SCL OEL..." for VtMinPu and VtResetPu

2024-09-25 15:36 UTC, joyelfeghali commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/StatorCurrentLimiters/Standard/BaseClasses/SclReferenceCurrent.mo
> +  //Input variable
variables

2024-09-25 15:42 UTC, joyelfeghali commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/StatorCurrentLimiters/Standard/BaseClasses/SclReferenceCurrent.mo
> +  parameter Types.CurrentModulePu IInstPu "Underexcited region instantaneous stator current limit in pu (base SnRef, UNom)";
SCL instantaneous stator current limit

2024-09-26 06:45 UTC, ErwanGuichard49 commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/OverExcitationLimiters/Standard/Oel2c.mo
> +  final parameter Types.Time tErr0 = tFcl - (K2 * (IScaled0Pu ^ C2 - 1) + (if IScaled0Pu <= 1 then FixedRu else FixedRd)) / KFb;
Done

2024-09-26 06:47 UTC, ErwanGuichard49 commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/OverExcitationLimiters/Standard/Oel2c.mo
> +  parameter Types.VoltageModulePu VInvMinPu "OEL minimum inverse time output";
Indeed

2024-09-26 07:00 UTC, ErwanGuichard49 commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/OverExcitationLimiters/Standard/Oel5c.mo
> +  parameter Types.VoltageModulePu VfeRefPu "Exciter field current reference setpoint in pu (base UNom)";
VfePu may be a voltage standing for a current, I could describe it as "Field current analog voltage in pu (user-selected base voltage)".

In AcRotatingExciter.mo, VfePu is a voltage described (as in Oel5c.mo) as "Field current signal in pu (user-selected base voltage)".

2024-09-26 07:08 UTC, ErwanGuichard49 commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/OverExcitationLimiters/Standard/Oel5c.mo
> +  parameter Types.VoltageModulePu IBiasPu "OEL reference bias in pu (base UNom)";
IBiasPu is like UOelPu a voltage in pu base UNom. I would keep the type and the description as they are.

2024-09-26 07:12 UTC, ErwanGuichard49 commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/OverExcitationLimiters/Standard/Oel5c.mo
> +  parameter Types.PerUnit IfdRef2Pu "OEL reference 2 in pu (base SnRef, user-selected base voltage)";
Agreed

2024-09-26 07:35 UTC, ErwanGuichard49 commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/OverExcitationLimiters/Standard/Oel4c.mo
> +  Modelica.Blocks.Logical.And and1 annotation(
Agreed, the And block was not needed.

2024-09-26 07:51 UTC, ErwanGuichard49 commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/StatorCurrentLimiters/Standard/Scl2c.mo
> +  final parameter Types.Time tErr0 = tScl - (K2 * (IScaled0Pu ^ C2 - 1) + (if IScaled0Pu <= 1 then FixedRu else FixedRd)) / KFb "Initial SCL timer error in s";
Done, with tScl instead of tFcl.

2024-09-26 12:12 UTC, ErwanGuichard49 commented on nrt/data/SMIB/IEEE/PmConstSt5bPss2bScl1c/SMIB.crv
There is no oelReferenceCurrent in Scl1c. There is one in Oel2c, but the initial output (case PmConstSt6cPss6cOel2c) is within the limits of this integrator.

2024-09-30 09:04 UTC, ErwanGuichard49 commented on dynawo/sources/Models/Modelica/PreassembledModels/NrtModels.txt
Agreed

2024-09-30 09:05 UTC, ErwanGuichard49 commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/StatorCurrentLimiters/Standard/Scl2c.mo
> +  parameter Types.VoltageModulePu VInvMinPu "SCL minimum inverse time output";
Corrected

2024-09-30 09:08 UTC, joyelfeghali approved these changes

2024-09-30 11:01 UTC, merged