#3112 [COLIB-NGC] add govSteamEU
dynawo/dynawo pull request #3366
Opened 2024-08-01 12:01 UTC by martinscripts

- Model is finished and ready to be reviewed. 
- OM SMIB test has been integrated in library

2024-10-08 13:27 UTC, joyelfeghali requested changes

2024-10-08 13:27 UTC, joyelfeghali commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/Governors/Standard/Steam/GovSteamEU.mo
> +  Modelica.Blocks.Interfaces.RealInput PRefPu(start = PRef0Pu) "Power reference value in pu (base PNomTurb) (generator convention)" annotation(Placement(visible = true, transformation(origin = {-156,
Could you make graphically all inputs aligned and have the same size? thanks

2024-10-14 11:15 UTC, martinscripts commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/Governors/Standard/Steam/GovSteamEU.mo
> +  parameter Types.Time tLpt = 0.45 "Low pressure turbine time constant in s, typical value = 0.45" annotation( Dialog(tab = "Turbine / boiler"));
an I also renamed tHpt to tHp

2024-10-14 11:20 UTC, martinscripts commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/Governors/Standard/Steam/GovSteamEU.mo
> +  Modelica.Blocks.Continuous.LimIntegrator limIntegratortRh(initType = Modelica.Blocks.Types.Init.InitialState,k = 1/tRh, outMax = PRhMaxPu, outMin = 0, y_start = if tRh > 0.0 then Pm0Pu else 0.0) an
I would say that those limits 

![image](https://github.com/user-attachments/assets/a33cb8d5-9811-4583-92f0-bcdde7283827)

already prevent values below zero, but the standard has this zero lower limit there, so we put it.

2024-10-14 11:22 UTC, martinscripts commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/Governors/Standard/Steam/GovSteamEU.mo
> +      final parameter Types.PerUnit initPcPu = Pm0Pu - min(max(KOmegaCor * (SystemBase.omegaRef0Pu - SystemBase.omega0Pu), OmegaOmegaMinPu), OmegaOmegaMaxPu) "Initialization helper for PcPu";
should it not be indented under the protected keyword?

2024-10-14 12:39 UTC, martinscripts commented on dynawo/sources/Models/Modelica/Dynawo/Examples/SMIB/Standard/GovSteamEuExcIEEEST4BPssIEEE2B2.mo
> +model GovSteamEuExcIEEEST4BPssIEEE2B2 "Active power variation on the load with governor GovSteamEU"
I renamed it 

GovSteamEuSt4b

to be consistent with GovCt2 (hence the small u in Eu) and with the other test cases (there is no PSS in this test case)

2024-10-14 12:41 UTC, martinscripts commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/Governors/Standard/Steam/GovSteamEU.mo
> +  Modelica.Blocks.Interfaces.RealInput fPu(start = SystemBase.omega0Pu) "Measured frequency of the grid in pu (base omegaRef0Pu/(2*pi))" annotation(Placement(visible = true, transformation(origin = {
no, because both are in per unit they dont need the 2pi factor.

2024-10-14 12:45 UTC, martinscripts commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/Governors/Standard/Steam/GovSteamEU.mo
> +  Modelica.Blocks.Interfaces.RealInput fRefPu(start = SystemBase.omegaRef0Pu) "Reference frequency in pu (base omegaRef0Pu/(2*pi))" annotation(Placement(visible = true, transformation(origin = {-155,
no, if I divide omegaRef0Pu, a pu value, by 2pi, it will be wrong. 
In per unit, f an omega should have the same initial value.

2024-10-14 13:28 UTC, martinscripts commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/Governors/Standard/Steam/GovSteamEU.mo
> +  final parameter Types.ActivePowerPu PRef0Pu = Pm0Pu;
I think you are right, I changed it to PGen0Pu initialization, and it did not affect steady state.

2024-10-14 13:43 UTC, martinscripts commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/Governors/Standard/Steam/GovSteamEU.mo
> +  parameter Types.Time tEht = 0.1 "Electro hydraulic transducer time constant in s, typical value = 0.1" annotation( Dialog(tab = "Grid connected control"));
that was an error, thanks.

2024-10-14 14:32 UTC, martinscripts commented
Hey @joyelfeghali, thank you for your feedback, I included the requests if I resolved the conversation -- the other conversations I answered, please have a look. 

Don't worry about the non-squashed commits -- I will squash when we finished.

2024-10-16 09:11 UTC, joyelfeghali requested changes
After these changes, you can squash the commits.

I will be building the Dynawo test case and comparing it to the one of OpenModelica

2024-10-16 09:11 UTC, joyelfeghali commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/Governors/Standard/Steam/GovSteamEU.mo
> +  parameter Types.Time tFp = 1e-9 "Power controller derivative numerical approximation time constant in s, typical value = 1e-9" annotation(
Could you remove the 1e-9 values, I had problems with GovCt2 in dynawo so I redruced the values to 1e-6, I prefer not having a default value

2024-10-16 10:53 UTC, martinscripts commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/Governors/Standard/Steam/GovSteamEU.mo
It is "GovSteamEu.mo" changed on my version of the branch. I dont know why github shows the old name

2024-10-16 10:57 UTC, martinscripts commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/Governors/Standard/Steam/GovSteamEU.mo
I needed to `git push --tags -f`, I think now it works

2024-10-16 11:22 UTC, martinscripts commented
fixed the naming now (GovSteamEu.mo)

ready to merge from my side

2024-10-23 08:50 UTC, joyelfeghali approved these changes

2024-10-23 08:51 UTC, merged