#3107 add govHydro4
dynawo/dynawo pull request #3393
Opened 2024-09-11 09:22 UTC by martinscripts

**Checklist before requesting a review**

*use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes*

- [ ] unit tests and non-regression tests were added (new model, new feature and bug fix)
- [ ] main documentation was updated (update of input/output file, 3rd party, model, repository organization, solver)
- [x] example documentations were updated (new example in examples folder)
- [ ] the corresponding milestone was added in the ticket and in this PR

2024-11-12 10:33 UTC, joyelfeghali requested changes

2024-12-03 14:33 UTC, martinscripts commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/Governors/Standard/Hydraulic/GovHydro4.mo
> +  Modelica.Blocks.Interfaces.RealInput PRefPu(start = PRef0Pu) "Reference power in pu (no constant base due to turbine characteristics" annotation(
not really, it is a value that does not correspond to a physical power. 
In the past, this "knob" has just been turned until the electrical power output is whatever was needed.

2024-12-03 14:52 UTC, martinscripts commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/Governors/Standard/Hydraulic/GovHydro4.mo
> +  Modelica.Blocks.Continuous.Integrator intTw(k = 1 / tW, y_start = Pm0Pu / ATurb + QNl) annotation(
@AGISTIN-Project Nils please answer

2024-12-03 15:41 UTC, martinscripts commented
Hey @joyelfeghali, I cared for most of the conversations (two are still open, one needs to be answered by nils) 
I also squashed and force-pushed.

2025-01-07 08:26 UTC, joyelfeghali approved these changes

2025-01-07 08:26 UTC, merged