#3392 save CPP tap changer internal variables in dump
dynawo/dynawo pull request #3401
Opened 2024-09-22 19:36 UTC by vermeulenthi

**Checklist before requesting a review**

*use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes*

- [x] unit tests and non-regression tests were added (new model, new feature and bug fix)
- [ ] main documentation was updated (update of input/output file, 3rd party, model, repository organization, solver)
- [ ] example documentations were updated (new example in examples folder)
- [ ] the corresponding milestone was added in the ticket and in this PR
- [ ] if this PR modifies the parameters or inputs/outputs of a model/solver: the corresponding xsl was added in util/xsl and platform DB were updated
- [ ] if this PR modifies a dictionary: the corresponding french dictionary was updated

2024-09-22 19:45 UTC, vermeulenthi commented
Open questions: 
- New file "-internalvariables.bin" is created. Another option would have been to recycle the ModelCPP dump/load parameter (less code change)
- All ModelPhaseTapChanger and ModelRatioTapChanger, minus the 'side' string, are dumped (does not include attributes from the parent ModelTapChanger class). Check which would be interesting to dump.
- StringSteam is passed through all functions, to dump only 1 file for the ModelNetwork. Another option would be to fetch data from included model and do all the serialization work in the ModelNetwork class.

2024-09-23 07:57 UTC, rosiereflo requested changes

2024-09-23 07:57 UTC, rosiereflo commented on dynawo/sources/Simulation/DYNSimulation.cpp
> +  model_->dumpInternalVariables(mapValues);
Should be hidden inside the dumpVariables

2024-09-23 07:57 UTC, rosiereflo commented on dynawo/sources/Modeler/Common/DYNModel.h
> +  virtual void dumpInternalVariables(std::map< std::string, std::string >& mapInternalVariables) = 0;
No need to have this visible at that level. Specializing the dumpVariables of components of the model network should be enough

2024-09-24 11:37 UTC, rosiereflo requested changes

2024-09-24 11:37 UTC, rosiereflo commented on dynawo/sources/Models/CPP/Common/DYNModelCPP.cpp
> +ModelCPP::dumpVariablesInStream(stringstream& streamVariables) {
const?

2024-09-24 11:37 UTC, rosiereflo commented on nrt/data/DynaWaltz/Nordic_DumpLoad/Events.dyd
> +    Copyright (c) 2023, RTE (http://www.rte-france.com)
2024

2024-09-24 15:03 UTC, vermeulenthi commented on dynawo/sources/Models/CPP/Common/DYNModelCPP.h
> +   * @copydoc SubModel::dumpParameters(std::map< std::string, std::string >& mapParameters)
ok, changed back.

2024-09-24 15:03 UTC, vermeulenthi commented on dynawo/sources/Models/CPP/Common/DYNModelCPP.cpp
> +ModelCPP::dumpVariablesInStream(stringstream& streamVariables) {
const added

2024-09-24 15:03 UTC, vermeulenthi commented on nrt/data/DynaWaltz/Nordic_DumpLoad/Events.dyd
> +    Copyright (c) 2023, RTE (http://www.rte-france.com)
2024 added

2024-09-25 08:31 UTC, rosiereflo approved these changes
Looks good. Did you run the internal tests?

2024-09-25 09:54 UTC, vermeulenthi commented
@rosiereflo Yes, tests and NRT ok.

2024-09-25 14:10 UTC, merged