#3395 Voltage values of VRRemote are now in Pu
dynawo/dynawo pull request #3407
Opened 2024-09-26 08:45 UTC by rosiereflo

closes #3395

**Checklist before requesting a review**

*use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes*

- [ ] unit tests and non-regression tests were added (new model, new feature and bug fix)
- [ ] main documentation was updated (update of input/output file, 3rd party, model, repository organization, solver)
- [ ] example documentations were updated (new example in examples folder)
- [ ] the corresponding milestone was added in the ticket and in this PR
- [ ] if this PR modifies the parameters or inputs/outputs of a model/solver: the corresponding xsl was added in util/xsl and platform DB were updated
- [ ] if this PR modifies a dictionary: the corresponding french dictionary was updated

2024-09-30 15:04 UTC, gaouizer approved these changes

2024-10-01 09:28 UTC, marcochiaramello approved these changes

2024-10-01 09:31 UTC, marcochiaramello requested changes

2024-10-01 09:31 UTC, marcochiaramello commented on nrt/data/DynaFlow/VRRemote/VRRemote.par
>      <par type="DOUBLE" name="vrremote_tIntegral" value="1"/>
the value here should be ailgned to waht is given by default in DFL

2024-10-01 11:40 UTC, joyelfeghali requested changes

2024-10-01 11:40 UTC, joyelfeghali commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Voltage/VRRemote.mo
> +  Modelica.Blocks.Interfaces.RealInput URefPu(start = URef0Pu) "Regulated voltage reference in per-unit" annotation(
in pu (base UNom)

2024-10-01 11:40 UTC, joyelfeghali commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Voltage/VRRemote.mo
> +  Modelica.Blocks.Interfaces.RealInput URegulatedPu(start = U0Pu) "Regulated voltage in per-unit" annotation(
in pu (base UNom)

2024-10-01 11:40 UTC, joyelfeghali commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Voltage/VRRemote.mo
> +  parameter Types.VoltageModule URef0Pu "Start value of the regulated voltage reference in per-unit";
in pu (base Unom) for U0Pu and URef0Pu

2024-10-02 07:41 UTC, rosiereflo commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Voltage/VRRemote.mo
> +  Modelica.Blocks.Interfaces.RealInput URefPu(start = URef0Pu) "Regulated voltage reference in per-unit" annotation(
done

2024-10-02 07:41 UTC, rosiereflo commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Voltage/VRRemote.mo
> +  parameter Types.VoltageModule URef0Pu "Start value of the regulated voltage reference in per-unit";
done

2024-10-02 07:41 UTC, rosiereflo commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Voltage/VRRemote.mo
> +  Modelica.Blocks.Interfaces.RealInput URegulatedPu(start = U0Pu) "Regulated voltage in per-unit" annotation(
done

2024-10-02 10:46 UTC, joyelfeghali approved these changes

2024-10-02 11:54 UTC, marcochiaramello approved these changes

2024-10-03 07:00 UTC, merged