#3419 High RAM usage during compilation of models PhotovoltaicsWeccVo…
dynawo/dynawo pull request #3430
Opened 2024-10-14 16:42 UTC by barondim

…ltageSourceA and B

**Checklist before requesting a review**

*use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes*

- [ ] unit tests and non-regression tests were added (new model, new feature and bug fix)
- [ ] main documentation was updated (update of input/output file, 3rd party, model, repository organization, solver)
- [ ] example documentations were updated (new example in examples folder)
- [x] the corresponding milestone was added in the ticket and in this PR
- [ ] if this PR modifies the parameters or inputs/outputs of a model/solver: the corresponding xsl was added in util/xsl and platform DB were updated
- [ ] if this PR modifies a dictionary: the corresponding french dictionary was updated

2024-10-21 08:57 UTC, gautierbureau requested changes

2024-10-21 08:57 UTC, gautierbureau commented on dynawo/sources/ModelicaCompiler/compileCppModelicaModelInDynamicLib.cmake.in
> +  set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} -O3 --param max-inline-insns-auto=19")  # since gcc-10, we have to lower max-inline-insns-auto parameter to prevent excessive RAM usage and o
can we activate it only if gcc > 9 ?

2024-11-06 12:52 UTC, rosiereflo approved these changes

2024-11-07 10:06 UTC, rosiereflo commented
@gautierbureau could you please review again as the PR is ready and validated?

2024-11-14 15:32 UTC, rosiereflo commented
@gautierbureau could you please take a look? The merge will be blocked as long as the PR will be in "changes requested" mode, and this issue happens on all recent OS

2024-11-15 13:48 UTC, gautierbureau approved these changes

2024-11-15 13:49 UTC, merged