#3499 Add variable impedant fault to library
dynawo/dynawo pull request #3503
Opened 2024-12-10 09:47 UTC by Philibert92

**Checklist before requesting a review**

*use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes*

- [ ] unit tests and non-regression tests were added (new model, new feature and bug fix)
- [ ] main documentation was updated (update of input/output file, 3rd party, model, repository organization, solver)
- [ ] example documentations were updated (new example in examples folder)
- [ ] the corresponding milestone was added in the ticket and in this PR
- [ ] if this PR modifies the parameters or inputs/outputs of a model/solver: the corresponding xsl was added in util/xsl and platform DB were updated
- [ ] if this PR modifies a dictionary: the corresponding french dictionary was updated

2024-12-10 10:05 UTC, joyelfeghali requested changes

2024-12-10 10:05 UTC, joyelfeghali commented on dynawo/sources/Models/Modelica/Dynawo/Examples/Wind/IEC/Neplan/WPP4ACurrentSource2020UDip.mo
> +equation
line skip

2024-12-10 10:05 UTC, joyelfeghali commented on dynawo/sources/Models/Modelica/Dynawo/Examples/Wind/IEC/Neplan/package.order
> +WPP4ACurrentSource2020UDip
could you also add it to Examples/Wind/IEC/Neplan/CMakeLists.txt?

2024-12-10 10:05 UTC, joyelfeghali commented on dynawo/sources/Models/Modelica/Dynawo/Examples/Wind/IEC/Neplan/WPP4ACurrentSource2020UDip.mo
could you also add reference .csv for this example?

2024-12-10 10:05 UTC, joyelfeghali commented on dynawo/sources/Models/Modelica/PreassembledModels/Ramp.xml
I think you accidentally removed this file

2024-12-10 10:05 UTC, joyelfeghali commented on examples/DynaSwing/IEC/Wind/Neplan/WPP4ACurrentSource2020UDip/WPP4ACurrentSource2020.crv
> +    Copyright (c) 2023, RTE (http://www.rte-france.com)
2024 for all copyright

2024-12-10 10:05 UTC, joyelfeghali commented on examples/DynaSwing/IEC/Wind/Neplan/WPP4ACurrentSource2020UDip/WPP4ACurrentSource2020.dyd
> +  <dyn:blackBoxModel id="ImpedantFault" lib="VariableImpedantFault" parFile="WPP4ACurrentSource2020.par" parId="ImpedantFault"/>
VariableImpedantFault.xml is missing from preassemble
Could you also add it to CMakeLists.xml and NrtModels.xml?

2024-12-10 17:37 UTC, joyelfeghali requested changes

2024-12-10 17:37 UTC, joyelfeghali commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Events/VariableImpedantFault.mo
> +    ZvPu * terminal.i = terminal.V - 0;
```suggestion
    ZvPu * terminal.i = terminal.V;
```

2024-12-10 17:37 UTC, joyelfeghali commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Events/VariableImpedantFault.mo
> +  Types.ComplexImpedancePu ZvPu;
definition

2024-12-10 17:37 UTC, joyelfeghali commented on dynawo/sources/Models/Modelica/Dynawo/Examples/Wind/IEC/Neplan/WPP4ACurrentSource2020UDip.mo
> +  annotation(
line skip here and at line 67

2024-12-10 17:37 UTC, joyelfeghali commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Events/VariableImpedantFault.mo
> +The line model is a classical Pi-line mode with the following equivalent circuit and conventions:<div><br></div><div>
Could you change the documentation?

2024-12-10 17:37 UTC, joyelfeghali commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Events/VariableImpedantFault.mo
> +model VariableImpedantFault "AC power line - PI model"
Could you change the description?

2024-12-10 17:37 UTC, joyelfeghali commented on dynawo/sources/Models/Modelica/PreassembledModels/VariableImpedantFault.xml
> +  <!-- Infinite bus with UPu, UPhase and OmegaRefPu given by tables as functions of time -->
Also here

2024-12-10 17:37 UTC, joyelfeghali commented on examples/DynaSwing/IEC/Wind/Neplan/WPP4ACurrentSource2020UDip/WPP4ACurrentSource2020.jobs
> +  <dyn:job name="WPP4ACurrentSource2020">
Could you add this jobs in nrt.py?

2024-12-11 08:33 UTC, Philibert92 commented on dynawo/sources/Models/Modelica/Dynawo/Examples/Wind/IEC/Neplan/WPP4ACurrentSource2020UDip.mo
> +  Dynawo.Electrical.Events.VariableImpedantFault variableImpedantFault(ImpedanceTableFile = "/home/philinux/dynawo/dynawo/examples/DynaSwing/IEC/Wind/Neplan/WPP4ACurrentSource2020UDip/TableVariableIm
I tried to shroten the path but it doesn't work. The file is not found anymore.

2024-12-11 09:16 UTC, joyelfeghali commented on dynawo/sources/Models/Modelica/Dynawo/Examples/Wind/IEC/Neplan/WPP4ACurrentSource2020UDip.mo
> +  Dynawo.Electrical.Events.VariableImpedantFault variableImpedantFault(ImpedanceTableFile = "/home/philinux/dynawo/dynawo/examples/DynaSwing/IEC/Wind/Neplan/WPP4ACurrentSource2020UDip/TableVariableIm
It depends on your OpenModelica repository, but at least here, you should remove your personal

2024-12-11 10:07 UTC, joyelfeghali commented on dynawo/sources/Models/Modelica/Dynawo/Examples/Wind/IEC/Neplan/WPP4ACurrentSource2020UDip.mo
Coud you add reference file for the OpenModelica example in Dynawo/Examples/Wind/IEC/Neplan/reference?

2024-12-11 10:34 UTC, joyelfeghali requested changes

2024-12-11 10:34 UTC, joyelfeghali commented on examples/DynaSwing/IEC/Wind/Neplan/WPP4ACurrentSource2020UDip/WPP4ACurrentSource2020.crv
> +  <curve model="WPP4A" variable="WPP_wPPControl_measurements_QGenNomPu"/>
Due to current development, these variable names have changed
```suggestion
  <curve model="WPP4A" variable="WPP_wPPControl_measurements_QPu"/>
```

2024-12-11 10:34 UTC, joyelfeghali commented on examples/DynaSwing/IEC/Wind/Neplan/WPP4ACurrentSource2020UDip/WPP4ACurrentSource2020.crv
> +  <curve model="WPP4A" variable="WPP_wPPControl_measurements_PGenNomPu"/>
```suggestion
  <curve model="WPP4A" variable="WPP_wPPControl_measurements_PPu"/>
```

2024-12-11 10:34 UTC, joyelfeghali commented on examples/DynaSwing/IEC/Wind/Neplan/WPP4ACurrentSource2020UDip/reference/outputs/curves/curves.csv
> +time;WPP4A_WPP_wPPControl_measurements_PGenNomPu;WPP4A_WPP_wPPControl_measurements_QGenNomPu;WPP4A_WPP_wPPControl_measurements_UPu;VariableImpedantFault_variableImpedantFault_ZvPu_re;VariableImpedant
```suggestion
time;WPP4A_WPP_wPPControl_measurements_PPu;WPP4A_WPP_wPPControl_measurements_QPu;WPP4A_WPP_wPPControl_measurements_UPu;VariableImpedantFault_variableImpedantFault_ZvPu_re;VariableImpedantFault_variableImpedantFault_ZvPu_im;
```

2024-12-11 10:34 UTC, joyelfeghali commented on dynawo/sources/Models/Modelica/Dynawo/Examples/Wind/IEC/Neplan/WPP4ACurrentSource2020UDip.mo
The simulation is failing now locally, does it work for you?

2024-12-11 16:13 UTC, Philibert92 commented on dynawo/sources/Models/Modelica/Dynawo/Examples/Wind/IEC/Neplan/WPP4ACurrentSource2020UDip.mo
I changed the precision step of the solver and it now seems to work. But it must be very sensitive.

2025-01-03 15:10 UTC, joyelfeghali commented on dynawo/sources/Models/Modelica/Dynawo/Examples/Wind/IEC/Neplan/WPP4ACurrentSource2020UDip.mo
It worked for me when the time step is reduced to 1e-4, could you set it to this value?

2025-01-03 15:11 UTC, joyelfeghali approved these changes
Could you : 
- rebase to master,
- change the dates to 2025, 
- and test the nrt you added? 

Then I can merge, thanks.

2025-01-06 14:36 UTC, merged