#2455 Replace all boost pointers by std pointers (Part. 5)
dynawo/dynawo pull request #3505
Opened 2024-12-11 16:29 UTC by barondim

**Checklist before requesting a review**

*use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes*

- [ ] unit tests and non-regression tests were added (new model, new feature and bug fix)
- [ ] main documentation was updated (update of input/output file, 3rd party, model, repository organization, solver)
- [ ] example documentations were updated (new example in examples folder)
- [x] the corresponding milestone was added in the ticket and in this PR
- [ ] if this PR modifies the parameters or inputs/outputs of a model/solver: the corresponding xsl was added in util/xsl and platform DB were updated
- [ ] if this PR modifies a dictionary: the corresponding french dictionary was updated

2024-12-11 18:39 UTC, barondim commented
- [ ] to be merged with https://github.com/dynawo/dynaflow-launcher/pull/813

2024-12-12 12:38 UTC, rosiereflo requested changes

2024-12-12 13:59 UTC, barondim commented on dynawo/sources/Modeler/Common/DYNDynamicData.h
> +#include "DYNConnectInterface.h"
unique_ptr<ConnectInterface> needs ConnectInterface to be a complete type to call the default destructor while it wasn't the case with shared_ptr<ConnectInterface>

2024-12-18 12:07 UTC, rosiereflo approved these changes

2024-12-18 12:08 UTC, merged