add Epri GFM (work in progress)
dynawo/dynawo pull request #3518
Opened 2024-12-20 15:03 UTC by martinscripts

@joyelfeghali, 
this work is in progress, we had problems with simualtion stability. 
Still, if you have time, you are welcome to look through the general structure and give feedback on that already.

2025-01-20 15:53 UTC, joyelfeghali requested changes

2025-01-20 15:53 UTC, joyelfeghali commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Converters/EpriGFM/Comptodq.mo
> +
Before I review the model, just some comments about the form : 

- copyright should be added before model definition
- Add description for each model
- define parameters
- Add description for each parameter, indicate unit and base if in pu, and convention (generator or receptor convention) for currents for example
- define inputs/outputs before other variables and blocks
-  Add description for each variable, indicate unit and base if in pu, and convention (generator or receptor convention) for currents for example
- define initial parameters
- define final parameters
- skip a line before "equation" and before "annotation"
- respect alphabetical order for parameters and input/output variables
- package.order should be in alphabetical order

Naming convention is described in here Dynawo.UsersGuide.NamingConvention.

For examples in OpenModelica, you should add a description of the test case and events, with figures. And add a reference file for the curves.

Finally, all new models should also be added to CMakeLists.txt, (in alphabetical order), or else we cannot compile in Dynawo

2025-01-28 10:00 UTC, joyelfeghali commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Converters/EpriGFM/EpriGFM.mo
> +  Dynawo.Electrical.Sources.InjectorURI injectorURI(i0Pu = i0Pu, u0Pu = u0Pu, uiPu(start = 0), urPu(start = 1)) annotation(
no modifiers for the start value, it should be generic

2025-01-28 10:01 UTC, joyelfeghali commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Converters/EpriGFM/EpriGFM.mo
> +  GFM gfm(DD = DD, DeltaOmegaMaxPu = DeltaOmegaMaxPu, DeltaOmegaMinPu = DeltaOmegaMinPu,DeltaVVId0 = DeltaVVId0, DeltaVVIq0 = DeltaVVIq0, IdPcc0Pu = 0, IqPcc0Pu = 0, K1 = K1, K2Dvoc = K2Dvoc, K2 = K2
no modifiers on start values, and also parameters for IdPcc0Pu, IqPcc0Pu  should be defined

2025-01-28 10:04 UTC, joyelfeghali commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Converters/EpriGFM/EpriGFM.mo
> +  Modelica.Blocks.Sources.Step PAux(height = 0.001, startTime = 70) annotation(
All the steps should be removed and put instead in the test case.

Here since it is a generic model you should only define them as inputs

2025-01-28 10:06 UTC, joyelfeghali commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Converters/EpriGFM/EpriGFM.mo
> +  injectorURI.switchOffSignal1.value = false;
Also the switch-off signals should be moved to the example, they should be defined in the model here.

It should be a similar model to what we have for wind turbines for instance

2025-01-30 11:18 UTC, martinscripts commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Converters/EpriGFM/package.order
> +GFM
done

2025-01-30 11:23 UTC, martinscripts commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Converters/EpriGFM/EpriGFM.mo
> +  Dynawo.Electrical.Controls.Converters.EpriGFM.EpriCurrentCtrl epriCurrentCtrl(IdConv0Pu = 0, IqConv0Pu = 0, KIi = KIi, KPi = KPi, LFilterPu = LFilterPu, Pref0Pu = Pref0Pu, RFilterPu = RFilterPu, tE
fixed

2025-01-30 11:29 UTC, martinscripts commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Converters/EpriGFM/LvrtFrz.mo
> +  Modelica.Blocks.Interfaces.RealInput UPu(start = 1) "q-axis current in the grid in pu (base UNom, SNom) (generator convention)" annotation(
this was a typo, it is fixed

2025-01-30 12:13 UTC, martinscripts commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Converters/EpriGFM/CurrentLimiter.mo
> +  Modelica.Blocks.Interfaces.RealOutput iqConvRefLimPu(start = 1) "limited q-axis current in pu (base UNom, SNom) (generator convention)" annotation(
agreed, done

2025-01-30 12:17 UTC, martinscripts commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Converters/EpriGFM/EpriCurrentCtrl.mo
> +  // inputs
done

2025-01-30 12:18 UTC, martinscripts commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Converters/EpriGFM/EpriCurrentCtrl.mo
> +  Modelica.Blocks.Interfaces.RealInput udFilterPu(start = 1) "d-axis voltage at the converter's capacitor in pu (base UNom)" annotation(
done

2025-01-30 13:14 UTC, martinscripts commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Converters/EpriGFM/EpriGFM.mo
> +  Modelica.Blocks.Sources.Step PAux(height = 0.001, startTime = 70) annotation(
done

2025-01-30 16:31 UTC, joyelfeghali commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Converters/EpriGFM/BaseControls/Comptodq.mo
> +  // inputs
Could you add description and start values for these inputs?

2025-01-30 16:32 UTC, joyelfeghali commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Converters/EpriGFM/BaseControls/CurrentLimiter.mo
> +  parameter Real Ipmax_pPu = IMaxPu;
descriptions for parameters and variables

2025-01-30 16:32 UTC, joyelfeghali commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Converters/EpriGFM/BaseControls/DQTrafo.mo
> +  Modelica.Blocks.Interfaces.RealInput theta annotation(
description + start value for theta

2025-01-30 16:32 UTC, joyelfeghali commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Converters/EpriGFM/BaseControls/DQTrafo.mo
> +  Modelica.Blocks.Interfaces.RealOutput urSourcePu annotation(
descriptions + start values for uiSourcePu and urSourcePu

2025-01-30 16:33 UTC, joyelfeghali commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Converters/EpriGFM/BaseControls/LvrtFrz.mo
> +  Modelica.Blocks.Interfaces.RealInput UPu(start = 1) "Voltage magnitude in pu (base UNom)" annotation(
start = U0Pu

2025-01-30 16:34 UTC, joyelfeghali commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Converters/EpriGFM/Parameters.mo
> +  parameter Types.ActivePowerPu Pref0Pu "Initial active power in pu" annotation(Dialog(tab = "General"));
add base

2025-01-30 16:34 UTC, joyelfeghali commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Converters/EpriGFM/Parameters.mo
> +  parameter Types.PerUnit IMaxPu "Max current in pu, example value = 1.05" annotation(Dialog(tab = "VoltageCtrl"));
base for pu

2025-01-30 16:35 UTC, joyelfeghali commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Converters/EpriGFM/Parameters.mo
> +  parameter Types.PerUnit BPu "Half-susceptance in pu (base SnRef), example value = 0" annotation(Dialog(tab = "Circuit"));
(base SnRef, UNom) for all these circuit parameters

2025-01-30 16:35 UTC, joyelfeghali commented on dynawo/sources/Models/Modelica/Dynawo/Examples/GridForming/GridForming.mo
> -/*
undo modifications here

2025-01-30 16:40 UTC, joyelfeghali commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Converters/EpriGFM/EpriGFM.mo
> +  BaseControls.GFM gfm(DD = DD, DeltaOmegaMaxPu = DeltaOmegaMaxPu, DeltaOmegaMinPu = DeltaOmegaMinPu, IdConv0Pu = 0, IqConv0Pu = 0, K1 = K1, K2 = K2, K2Dvoc = K2Dvoc, KD = KD, MF = MF, OmegaFlag = Om
```suggestion
  BaseControls.GFM gfm(DD = DD, DeltaOmegaMaxPu = DeltaOmegaMaxPu, DeltaOmegaMinPu = DeltaOmegaMinPu, IdConv0Pu = IdConv0Pu, IqConv0Pu = IqConv0Pu, K1 = K1, K2 = K2, K2Dvoc = K2Dvoc, KD = KD, MF = MF, OmegaFlag = OmegaFlag, PFilter0Pu = PFilter0Pu, PRef0Pu = PRef0Pu, QFilter0Pu = QFilter0Pu, QRef0Pu = QRef0Pu, Theta0 = Theta0, UFilterRef0Pu = UFilterRef0Pu, tF = tF, tR = tR, tV = tV) annotation(
```

2025-01-31 13:43 UTC, martinscripts commented on dynawo/sources/Models/Modelica/Dynawo/Examples/GridForming/GridForming.mo
> -/*
OMEdits autoformat at work :D 
done

2025-02-03 11:23 UTC, martinscripts commented
We fixed the initialization inconsistency, I just force-pushed again.

2025-02-03 11:23 UTC, martinscripts commented
@joyelfeghali

2025-02-03 12:28 UTC, joyelfeghali commented
> We fixed the initialization inconsistency, I just force-pushed again.

Deal, thank you

2025-02-12 14:37 UTC, joyelfeghali requested changes

2025-02-12 14:37 UTC, joyelfeghali commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Converters/EpriGFM/BaseControls/GFM.mo
> +  Modelica.Blocks.Continuous.Integrator integrator2(k = 314.15, y_start = Theta0) annotation(
why the gain k = 314.15?

2025-02-12 14:37 UTC, joyelfeghali commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Converters/EpriGFM/BaseControls/GFM.mo
> +  Modelica.Blocks.Math.Add addOmegaBasePu annotation(
why do we add 1?
is it the omegaRef0Pu that we removed?

2025-02-12 15:14 UTC, AGISTIN-Project commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Converters/EpriGFM/BaseControls/EpriCurrentCtrl.mo
> +  Modelica.Blocks.Math.Product product1 annotation(
I did this in order to make it easier to understand, that the filter reactance is used. You can change this.

2025-02-12 15:16 UTC, joyelfeghali commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Converters/EpriGFM/BaseControls/EpriCurrentCtrl.mo
> +  Modelica.Blocks.Math.Product product1 annotation(
I was mainly wondering if omega * XPu is equivalent to omega * LFilter. If omega is different than 1

2025-02-12 15:17 UTC, AGISTIN-Project commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Converters/EpriGFM/BaseControls/CurrentLimiter.mo
> +      idConvRefLimPu = -Ipmax_pPu;
I think the model is a generic one that can also be used for storage. So, negative currents are needed.

2025-02-12 15:23 UTC, AGISTIN-Project commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Converters/EpriGFM/BaseControls/EpriVoltageCtrl.mo
> +  Modelica.Blocks.Math.Gain gainInvertSign(k = -1) annotation(
The negative sign is used, because in the test with PLL mode it was needed to get the correct direction of Q. I can try to test again.

2025-02-12 15:26 UTC, AGISTIN-Project commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Converters/EpriGFM/BaseControls/EpriVoltageCtrl.mo
> +  Modelica.Blocks.Math.Gain gainPiV(k = KPp) annotation(
There are 4 variables for the controllers in this block:
KPv Voltage control proportional gain 0.5
KIv Voltage control integral gain 
KPp Active power proportional gain 
KIp Active power integral gain

2025-02-12 15:32 UTC, AGISTIN-Project commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Converters/EpriGFM/BaseControls/GFM.mo
> +  Modelica.Blocks.Math.Add addMinusOmega0(k2 = -1) annotation(
The GFM model only works with the speed deviation. So I subtracted nominal speed.

2025-02-12 15:34 UTC, AGISTIN-Project commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Converters/EpriGFM/BaseControls/GFM.mo
> +  Modelica.Blocks.Continuous.FirstOrder lagOmega(T = tF, k = 1) annotation(
Also in the documentation, this part works as a first-order filter. Now, it is easier to understand how the model works.

2025-02-12 15:34 UTC, AGISTIN-Project commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Converters/EpriGFM/BaseControls/GFM.mo
> +  Modelica.Blocks.Continuous.Integrator integrator2(k = 314.15, y_start = Theta0) annotation(
going back from pu to rad, which is needed for the correct dq transform.

2025-02-12 15:36 UTC, AGISTIN-Project commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Converters/EpriGFM/BaseControls/GFM.mo
> +  Modelica.Blocks.Math.Add addOmegaBasePu annotation(
it is added to allow plotting as actual speed not just deviation and is need for forwarding with XPu (deviation would not work there)

2025-02-12 15:36 UTC, joyelfeghali commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Converters/EpriGFM/BaseControls/EpriVoltageCtrl.mo
> +  Modelica.Blocks.Math.Gain gainInvertSign(k = -1) annotation(
should the iqConvRef start value be then :   iqConvRefPu(start = -  IqConv0Pu) ?

2025-02-12 15:36 UTC, joyelfeghali commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Converters/EpriGFM/BaseControls/EpriVoltageCtrl.mo
> +  Modelica.Blocks.Math.Gain gainInvertSign(k = -1) annotation(
and what about gainInvertSign2?

2025-02-12 15:43 UTC, AGISTIN-Project commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Converters/EpriGFM/BaseControls/GFM.mo
> +  Modelica.Blocks.Sources.IntegerConstant constOmegaFlag(k = OmegaFlag) annotation(
It should be - 0=GFL, 1=droop, 2=VSM, 3=dVOC

I will check again.

2025-02-12 15:45 UTC, joyelfeghali commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Converters/EpriGFM/BaseControls/GFM.mo
> +  Modelica.Blocks.Continuous.Integrator integrator2(k = 314.15, y_start = Theta0) annotation(
Okay, but I am a bit lost, how get 314.15?

2025-02-12 15:46 UTC, AGISTIN-Project commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Converters/EpriGFM/BaseControls/GFM.mo
> +  Modelica.Blocks.Sources.RealExpression udFilterRefPu3(y = udFilterRefPu) annotation(
Sorry, I do not know, what you mean.

2025-02-12 15:47 UTC, AGISTIN-Project commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Converters/EpriGFM/BaseControls/GFM.mo
> +  Modelica.Blocks.Math.Gain gainMinusOne(k = 1) annotation(
You are right, I can be removed.

2025-02-12 15:47 UTC, joyelfeghali commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Converters/EpriGFM/BaseControls/GFM.mo
> +  Modelica.Blocks.Sources.RealExpression udFilterRefPu3(y = udFilterRefPu) annotation(
why this value is taken here and not integrator1.y ?

2025-02-12 15:50 UTC, AGISTIN-Project commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Converters/EpriGFM/BaseControls/DQTrafo.mo
> +  Dynawo.Electrical.Controls.PLL.PLL pll(Ki = 700, Kp = 20, OmegaMaxPu = 1.5, OmegaMinPu = 0.5, u0Pu = Complex(1.0, 0)) annotation(
I have overseen the hardcoded values. 
The PLL is also used for damping in VSM mode.
Only one PLL is needed. I used this one, too, in order to make sure, that the angle signals are not mixed up.

2025-02-12 15:54 UTC, AGISTIN-Project commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Converters/EpriGFM/BaseControls/Comptodq.mo
> +  Modelica.Blocks.Sources.Constant one(k = 0) annotation(
yes

2025-02-12 15:57 UTC, joyelfeghali commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Converters/EpriGFM/BaseControls/GFM.mo
> +  Modelica.Blocks.Sources.IntegerConstant constOmegaFlag(k = OmegaFlag) annotation(
okay, I just wanted to make sure that 0 = GFL corresponds to what they name 4. Phase Locked Loop (PLL) based GFM 

because on the figures, the just say that the options are 0,1,2,3

2025-02-13 07:56 UTC, AGISTIN-Project commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Converters/EpriGFM/BaseControls/GFM.mo
> +  Modelica.Blocks.Sources.IntegerConstant constOmegaFlag(k = OmegaFlag) annotation(
The mode number+1 is the switch connection - GFL->1, VSM->2 etc.

2025-02-14 10:33 UTC, joyelfeghali commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Converters/EpriGFM/BaseControls/DQTrafo.mo
> +  Dynawo.Electrical.Controls.PLL.PLL pll(Ki = 700, Kp = 20, OmegaMaxPu = 1.5, OmegaMinPu = 0.5, u0Pu = Complex(1.0, 0)) annotation(
Following this question  : 
In Comptodq : the measured injection voltage will be 0 if freeze  = true. Was there a reason this was not implemented in the PLL of DQTrafo.mo

2025-02-17 08:00 UTC, AGISTIN-Project commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Converters/EpriGFM/BaseControls/EpriCurrentCtrl.mo
> +  Modelica.Blocks.Math.Product product1 annotation(
it is the same

2025-02-17 08:02 UTC, AGISTIN-Project commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Converters/EpriGFM/BaseControls/DQTrafo.mo
> +  Dynawo.Electrical.Controls.PLL.PLL pll(Ki = 700, Kp = 20, OmegaMaxPu = 1.5, OmegaMinPu = 0.5, u0Pu = Complex(1.0, 0)) annotation(
I just have overseen to freeze the PLL.

2025-02-17 08:03 UTC, AGISTIN-Project commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Converters/EpriGFM/BaseControls/GFM.mo
> +  Modelica.Blocks.Continuous.Integrator integrator2(k = 314.15, y_start = Theta0) annotation(
2*pi*50

2025-02-17 08:17 UTC, AGISTIN-Project commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Converters/EpriGFM/BaseControls/EpriVoltageCtrl.mo
> +  Modelica.Blocks.Math.Gain gainPiV(k = KPp) annotation(
you are right, KPv is correct

2025-02-17 08:27 UTC, AGISTIN-Project commented on dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Converters/EpriGFM/BaseControls/EpriVoltageCtrl.mo
> +  Modelica.Blocks.Math.Gain gainInvertSign(k = -1) annotation(
iqConvRefPu(start = - IqConv0Pu), yes

In the simulation it seems to be correct with the different signs.

2025-03-03 16:41 UTC, merged